//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGESDOC.Request
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActividadProtocoloRequest
    {
        public int id_actividad_proto { get; set; }
        public Nullable<int> id_protocolo { get; set; }
        public Nullable<int> id_est_pro { get; set; }
        public Nullable<System.DateTime> fecha_registro { get; set; }
    
        public virtual EstadosDelProtocoloRequest estados_del_protocolo { get; set; }
        public virtual ProtocoloRequest protocolo { get; set; }
    }
}
