//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGESDOC.Request
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConsultarDbGeneralMaeAreaProduccionRequest
    {
        public int id_area_produccion { get; set; }
        public Nullable<int> id_zona_produccion { get; set; }
        public Nullable<int> id_estado_area_pro { get; set; }
        public Nullable<int> id_tipo_area_pro { get; set; }
        public string estado { get; set; }
        public string cod_zona_produccion { get; set; }
        public string union_europea { get; set; }
        public string cod_union_europea { get; set; }
        public string cod_area_produccion { get; set; }
        public string nombre { get; set; }
        public string tipo_area { get; set; }
    }
}
