//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGESDOC.Request
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConsultaPendientesSanipesDetalleRequest
    {
        public string hoja_tramite { get; set; }
        public System.DateTime fecha_emision { get; set; }
        public Nullable<int> tupa { get; set; }
        public string asunto_tupa { get; set; }
        public string estado { get; set; }
        public System.DateTime fecha_envio { get; set; }
        public Nullable<System.DateTime> fecha_recepcion { get; set; }
        public string oficina { get; set; }
        public string asunto { get; set; }
        public string destino { get; set; }
        public string persona_envia { get; set; }
    }
}
