//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGESDOC.Request
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConsultaDbGeneralMaeFacturaRequest
    {
        public int id_factura { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string fecha_text { get; set; }
        public string comprobante { get; set; }
        public string importe { get; set; }
        public string tupa_serv { get; set; }
        public string valor_fact_exp { get; set; }
        public string documento { get; set; }
        public string externo { get; set; }
        public string direccion { get; set; }
        public string operaciones { get; set; }
        public string tipo_factura { get; set; }
        public string usuario_registro { get; set; }
        public string ruta_pdf { get; set; }
        public Nullable<int> id_operacion { get; set; }
    }
}
