//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGESDOC.Request
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConsultarPersonaTelefonoRequest
    {
        public int id_persona_telefono { get; set; }
        public string persona_num_documento { get; set; }
        public string telefono1 { get; set; }
        public string activo { get; set; }
    }
}
