//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGESDOC.Request
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConsultarOficinaDireccionLegalRequest
    {
        public Nullable<int> id_oficina_direccion_legal { get; set; }
        public int id_sede { get; set; }
        public string ruc { get; set; }
        public string direccion { get; set; }
        public string ubigeo { get; set; }
        public string fecha_registro { get; set; }
        public string fecha_desactivado { get; set; }
        public Nullable<int> activo { get; set; }
        public string id_ubigeo { get; set; }
        public string nom_sede { get; set; }
        public string nom_direccion { get; set; }
        public string nom_referencia { get; set; }
    }
}
