//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGESDOC.Request
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConsultarPendientesHtParaAdjuntar20190104Request
    {
        public int oficina_destino { get; set; }
        public string oficina { get; set; }
        public string persona_num_documento { get; set; }
        public string nombre { get; set; }
        public string hoja_tramite { get; set; }
    }
}
