//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGESDOC.Request
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConsultarTipoActividadPlantaRequest
    {
        public int id_tipo_actividad { get; set; }
        public string nombre { get; set; }
        public Nullable<int> id_tipo_planta { get; set; }
        public string ruta_ftp { get; set; }
    }
}
