//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGESDOC.Request
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConsultaFacturasRequest
    {
        public int id_factura { get; set; }
        public Nullable<int> num1_fact { get; set; }
        public Nullable<int> num2_fact { get; set; }
        public Nullable<System.DateTime> fecha_fact { get; set; }
        public Nullable<decimal> importe_total { get; set; }
        public Nullable<System.DateTime> fecha_registro { get; set; }
        public string usuario_registro { get; set; }
        public string activo { get; set; }
        public Nullable<int> id_tipo_factura { get; set; }
        public string tipo_factura { get; set; }
    }
}
