//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGESDOC.Request
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConsultaReporteDiarioSerie1Request
    {
        public string num_fact { get; set; }
        public string fecha { get; set; }
        public string documento { get; set; }
        public string datos { get; set; }
        public string concepto { get; set; }
        public string expediente { get; set; }
        public int cantidad { get; set; }
        public string tupa { get; set; }
        public Nullable<decimal> importe_total { get; set; }
        public string operacion { get; set; }
        public string fecha_operacion { get; set; }
        public int id_factura { get; set; }
        public Nullable<int> id_tipo_factura { get; set; }
        public string fecha_num { get; set; }
        public string n_oficina_crea { get; set; }
    }
}
