//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGESDOC.Request
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConsultaFacturasRequest
    {
        public int id_factura { get; set; }
        public Nullable<int> num1_fact { get; set; }
        public Nullable<int> num2_fact { get; set; }
        public Nullable<System.DateTime> fecha_fact { get; set; }
        public Nullable<decimal> importe_total { get; set; }
        public Nullable<System.DateTime> fecha_registro { get; set; }
        public string usuario_registro { get; set; }
        public string activo { get; set; }
        public Nullable<int> id_tipo_factura { get; set; }
        public string tipo_factura { get; set; }
    }
}
