//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGESDOC.Request
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConsultaReciboSerie1Request
    {
        public int id_factura { get; set; }
        public string nombre { get; set; }
        public string direccion { get; set; }
        public string ruc_dni { get; set; }
        public string fecha_emision { get; set; }
        public string dia { get; set; }
        public string año { get; set; }
        public string mes_text { get; set; }
        public string letra_importe { get; set; }
        public Nullable<decimal> importe_total { get; set; }
        public Nullable<int> decimal_text { get; set; }
        public string nombre_vfe { get; set; }
        public string num_fact { get; set; }
        public string operacion { get; set; }
        public string fecha_operacion { get; set; }
        public string tupa_serv { get; set; }
        public Nullable<int> cantidad { get; set; }
    }
}
