//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGESDOC.Request
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetSegDocRequest
    {
        public int id_det_doc { get; set; }
        public int id_documento_seg { get; set; }
        public int id_seguimiento { get; set; }
        public string activo { get; set; }
    
        public virtual DocumentoSeguimientoRequest documento_seguimiento { get; set; }
        public virtual SeguimientoDhcpaRequest seguimiento_dhcpa { get; set; }
    }
}
