//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGESDOC.Request
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentoSeguimientoRequest
    {
        public int id_documento_seg { get; set; }
        public byte id_tipo_documento { get; set; }
        public Nullable<int> num_documento { get; set; }
        public string nom_documento { get; set; }
        public string asunto { get; set; }
        public Nullable<System.DateTime> fecha_documento { get; set; }
        public Nullable<System.DateTime> fecha_crea { get; set; }
        public string usuario_crea { get; set; }
        public Nullable<int> oficina_crea { get; set; }
        public Nullable<System.DateTime> fecha_recepcion_sdhpa { get; set; }
        public string usuario_recepcion_sdhpa { get; set; }
        public Nullable<System.DateTime> fecha_asignacion_evaluador { get; set; }
        public string evaluador { get; set; }
        public Nullable<System.DateTime> fecha_recibido_evaluador { get; set; }
        public string estado { get; set; }
        public string indicador { get; set; }
        public Nullable<int> id_servicio_dhcpa { get; set; }
        public Nullable<System.DateTime> fecha_od { get; set; }
        public string usuario_od { get; set; }
        public string expedientes_relacion { get; set; }
        public string ruta_pdf { get; set; }
        public string archivo_pdf { get; set; }
        public Nullable<int> folios { get; set; }
        public string nom_ofi_crea { get; set; }
    
        public virtual List<DetDocFactRequest> det_doc_fact { get; set; }
        public virtual List<DetSegDocRequest> det_seg_doc { get; set; }
        public virtual TipoDocumentoRequest tipo_documento { get; set; }
        public virtual List<DocumentoSeguimientoAdjuntoRequest> documento_seguimiento_adjunto { get; set; }
    }
}
