//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGESDOC.Request
{
    using System;
    using System.Collections.Generic;
    
    public partial class EspeciesHabilitacionesRequest
    {
        public int id_det_espec_hab { get; set; }
        public string codigo_especie { get; set; }
        public string activo { get; set; }
    
        public virtual List<ProtocoloEspecieRequest> protocolo_especie { get; set; }
    }
}
