//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGESDOC.Request
{
    using System;
    using System.Collections.Generic;
    
    public partial class FilialDhcpaRequest
    {
        public int id_filial { get; set; }
        public string nombre { get; set; }
        public string tp_e_i { get; set; }
        public Nullable<int> sol_insp { get; set; }
        public Nullable<int> id_od_insp { get; set; }
    }
}
