//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGESDOC.Request
{
    using System;
    using System.Collections.Generic;
    
    public partial class FilialDhcpaRequest
    {
        public int id_filial { get; set; }
        public string nombre { get; set; }
        public string tp_e_i { get; set; }
        public Nullable<int> sol_insp { get; set; }
        public Nullable<int> id_od_insp { get; set; }
    }
}
