//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGESDOC.Request
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProtocoloEmbarcacionRequest
    {
        public int id_det_pro_hab { get; set; }
        public Nullable<int> id_protocolo { get; set; }
        public string nom_embarcacion { get; set; }
        public Nullable<int> representante_legal { get; set; }
        public Nullable<int> direccion_legal { get; set; }
        public Nullable<int> id_tip_pro_emb { get; set; }
        public string resolucion { get; set; }
        public string direccion_persona_natural { get; set; }
        public Nullable<int> id_persona_telefono { get; set; }
    
        public virtual ProtocoloRequest protocolo { get; set; }
    }
}
