//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGESDOC.Request
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProtocoloConcesionRequest
    {
        public int id_det_pro_conce { get; set; }
        public Nullable<int> id_protocolo { get; set; }
        public Nullable<int> id_concesion { get; set; }
        public string resolucion { get; set; }
        public Nullable<System.DateTime> fecha_resolucion { get; set; }
        public Nullable<int> id_tip_act_conce { get; set; }
        public Nullable<int> direccion_legal { get; set; }
        public Nullable<int> representante_legal { get; set; }
        public Nullable<decimal> area_ha { get; set; }
        public Nullable<decimal> total_ha { get; set; }
        public Nullable<decimal> lote { get; set; }
        public Nullable<decimal> espejo_agua { get; set; }
        public Nullable<decimal> area { get; set; }
        public Nullable<decimal> capacidad_produccion { get; set; }
        public string direccion_legal_dni { get; set; }
        public Nullable<int> representante_legal_dni { get; set; }
    
        public virtual ProtocoloRequest protocolo { get; set; }
    }
}
