//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGESDOC.Request
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProtocoloPlantaRequest
    {
        public int id_dat_pro_pla { get; set; }
        public Nullable<int> id_protocolo { get; set; }
        public Nullable<int> direccion_legal { get; set; }
        public Nullable<int> representante_legal { get; set; }
        public string licencia_operacion { get; set; }
        public string ind_concha_abanico { get; set; }
        public string ind_otros { get; set; }
        public string ind_peces { get; set; }
        public string ind_crustaceos { get; set; }
        public Nullable<int> id_tipo_ch { get; set; }
        public string activo { get; set; }
    
        public virtual ProtocoloRequest protocolo { get; set; }
        public virtual TipoConsumoHumanoRequest tipo_consumo_humano { get; set; }
    }
}
