//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGESDOC.Request
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProtocoloAutorizacionInstalacionRequest
    {
        public int id_pro_autorizacion_instalacion { get; set; }
        public Nullable<int> id_protocolo { get; set; }
        public string ruc { get; set; }
        public Nullable<int> id_sede { get; set; }
        public Nullable<int> id_representante_legal { get; set; }
        public Nullable<int> id_tipo_autorizacion_instalacion { get; set; }
        public string actividad { get; set; }
    
        public virtual ProtocoloRequest protocolo { get; set; }
        public virtual TipoAutorizacionInstalacionRequest tipo_autorizacion_instalacion { get; set; }
    }
}
