//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGESDOC.Request
{
    using System;
    using System.Collections.Generic;
    
    public partial class PtocoloTransporteXIdTransporte2018V1Request
    {
        public string razon_social { get; set; }
        public string direccion_legal { get; set; }
        public string representante_legal { get; set; }
        public string infra_pesq { get; set; }
        public int id_transporte { get; set; }
        public string placa { get; set; }
        public string cod_habilitacion { get; set; }
        public Nullable<int> id_tipo_carroceria { get; set; }
        public string nombre_carroceria { get; set; }
        public Nullable<int> id_um { get; set; }
        public string nombre_um { get; set; }
        public string siglas_um { get; set; }
        public string carga_util { get; set; }
        public string estado { get; set; }
        public string nombre_estado { get; set; }
        public string acta_inspeccion { get; set; }
        public string informe_auditoria { get; set; }
        public string informe_tecnico_evaluacion { get; set; }
        public string fecha_inicio { get; set; }
        public string fecha_fin { get; set; }
        public string fecha_emision { get; set; }
        public string nombre_protocolo { get; set; }
        public string expediente { get; set; }
        public int id_tipo_furgon { get; set; }
        public string nombre_tipo_furgon { get; set; }
        public int id_protocolo { get; set; }
        public string informe_sdhpa { get; set; }
    }
}
