//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGESDOC.Request
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoTramiteRequest
    {
        public byte id_tipo_tramite { get; set; }
        public string nombre { get; set; }
    
        public virtual List<HojaTramiteRequest> hoja_tramite { get; set; }
    }
}
