//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGESDOC.Request
{
    using System;
    using System.Collections.Generic;
    
    public partial class VersionSolicitudRequest
    {
        public int id_version_sol { get; set; }
        public Nullable<int> numero_version { get; set; }
        public string activo { get; set; }
        public Nullable<System.DateTime> fecha_crea { get; set; }
        public string usuario_crea { get; set; }
    
        public virtual List<SolicitudInspeccionRequest> solicitud_inspeccion { get; set; }
    }
}
