//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGESDOC.Response
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActividadProtocoloResponse
    {
        public int id_actividad_proto { get; set; }
        public Nullable<int> id_protocolo { get; set; }
        public Nullable<int> id_est_pro { get; set; }
        public Nullable<System.DateTime> fecha_registro { get; set; }
    
        public virtual EstadosDelProtocoloResponse estados_del_protocolo { get; set; }
        public virtual ProtocoloResponse protocolo { get; set; }
    }
}
