//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGESDOC.Response
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConsultarDbGeneralMaeZonaProduccionResponse
    {
        public int id_zona_produccion { get; set; }
        public string activo { get; set; }
        public string union_europea { get; set; }
        public string cod_union_europea { get; set; }
        public string ubigeo { get; set; }
        public string departamento { get; set; }
        public string provincia { get; set; }
        public string distrito { get; set; }
        public string cod_zona_produccion { get; set; }
        public string nombre { get; set; }
    }
}
