//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGESDOC.Response
{
    using System;
    using System.Collections.Generic;

    public partial class ConsultarDbGeneralMaeAlmacenSedeResponse
    {
        public string externo { get; set; }
        public string direccion { get; set; }
        public string nom_cod_habilitante { get; set; }
        public string nom_actividad { get; set; }
        public string nom_filial { get; set; }
        public string ruta_pdf { get; set; }


        public string genera_data_externo { get; set; }
        public string genera_data_direccion { get; set; }
        public string genera_data_actividad { get; set; }
        public string genera_data_codigo_habilitacion { get; set; }
        public string genera_data_archivo { get; set; }        

    }
}
