//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGESDOC.Response
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConsultaExpedienteXExpedienteResponse
    {
        public string expediente { get; set; }
        public Nullable<int> id_expediente { get; set; }
        public int id_seguimiento { get; set; }
        public string num_documento { get; set; }
        public string externo { get; set; }
        public string direccion { get; set; }
        public string evaluador { get; set; }
    }
}
