//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGESDOC.Response
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConsultarDbGeneralMaeAlmacenSedeResponse
    {
        public int id_almacen { get; set; }
        public Nullable<int> id_sede { get; set; }
        public Nullable<int> id_codigo_almacen { get; set; }
        public Nullable<int> num_almacen { get; set; }
        public string nom_almacen { get; set; }
        public string codigo_habilitante { get; set; }
        public Nullable<int> id_filial { get; set; }
        public Nullable<int> id_actividad_almacen { get; set; }
        public Nullable<System.DateTime> fecha_registro { get; set; }
        public string usuario_registro { get; set; }
        public Nullable<System.DateTime> fecha_modifica { get; set; }
        public string usuario_modifica { get; set; }
        public Nullable<System.DateTime> fecha_desactivado { get; set; }
        public string usuario_desactivado { get; set; }
        public string activo { get; set; }
    }
}
