//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGESDOC.Response
{
    using System;
    using System.Collections.Generic;

    public partial class ConsultarDbGeneralMaeConcesionResponse
    {
        public string ruta_pdf { get; set; }

        public string genera_data_externo { get; set; }
        public string genera_data_actividad { get; set; }
        public string genera_data_codigo_concesion { get; set; }
        public string genera_data_departamento { get; set; }
        public string genera_data_provincia { get; set; }
        public string genera_data_distrito { get; set; }
        public string genera_data_ubicacion { get; set; }
        public string genera_data_archivos { get; set; }
    }
}
