//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGESDOC.Response
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConsultarActvAlmacenResponse
    {
        public int id_actividad_almacen { get; set; }
        public string nombre_actividad { get; set; }
        public string ruta_pdf { get; set; }
        public string activo { get; set; }
    }
}
