//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGESDOC.Response
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConsultaProtocolosAiResponse
    {
        public int id_protocolo { get; set; }
        public Nullable<int> id_seguimiento { get; set; }
        public string nombre { get; set; }
        public Nullable<System.DateTime> fecha_inicio { get; set; }
        public Nullable<System.DateTime> fecha_fin { get; set; }
        public Nullable<System.DateTime> fecha_registro { get; set; }
        public string evaluador { get; set; }
        public string activo { get; set; }
        public Nullable<int> id_est_pro { get; set; }
        public Nullable<int> id_protocolo_reemplaza { get; set; }
        public string ruta_pdf { get; set; }
    }
}
