//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGESDOC.Response
{
    using System;
    using System.Collections.Generic;

    public partial class ConsultaEmbarcacionesResponse
    {
        public string nombre_estado { get; set; }
        public string nombre_tipo_embarcacion { get; set; }
        public string nombre_actividad { get; set; }
        public string cod_habilitante { get; set; }


        public string genera_data_matricula { get; set; }
        public string genera_data_nombre { get; set; }
        public string genera_data_actividad { get; set; }
        public string genera_data_codigo_habilitacion { get; set; }
        public string genera_data_tipo_embarcacion { get; set; }
        public string genera_data_archivos { get; set; }


    }
}
