//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGESDOC.Response
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConstanciaHaccpResponse
    {
        public int id_constancia_haccp { get; set; }
        public Nullable<int> id_seguimiento { get; set; }
        public string nombre { get; set; }
        public string activo { get; set; }
        public Nullable<System.DateTime> fecha_registro { get; set; }
        public string usuario_registro { get; set; }
    
        public virtual SeguimientoDhcpaResponse seguimiento_dhcpa { get; set; }
    }
}
