//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGESDOC.Response
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConsultarDbGeneralMaeConcesionResponse
    {
        public int id_concesion { get; set; }
        public Nullable<int> id_area_produccion { get; set; }
        public Nullable<int> id_tipo_concesion { get; set; }
        public string activo { get; set; }
        public string ruc { get; set; }
        public string ubigeo { get; set; }
        public string codigo_habilitacion { get; set; }
        public string razon_social { get; set; }
        public string departamento { get; set; }
        public string provincia { get; set; }
        public string distrito { get; set; }
        public string ubicacion { get; set; }
        public string cod_area_produccion { get; set; }
        public string nombre_area_produccion { get; set; }
        public Nullable<int> id_zona_produccion { get; set; }
        public string cod_zona_produccion { get; set; }
        public string nombre_zona_produccion { get; set; }
        public string partida_registral { get; set; }
        public string tipo_concesion { get; set; }
        public Nullable<int> id_tip_act_conce { get; set; }
        public string actividad_concesion { get; set; }
    }
}
