//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGESDOC.Response
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConsultaReciboSerie1Response
    {
        public int id_factura { get; set; }
        public string nombre { get; set; }
        public string direccion { get; set; }
        public string ruc_dni { get; set; }
        public string fecha_emision { get; set; }
        public string dia { get; set; }
        public string año { get; set; }
        public string mes_text { get; set; }
        public string letra_importe { get; set; }
        public Nullable<decimal> importe_total { get; set; }
        public Nullable<int> decimal_text { get; set; }
        public string nombre_vfe { get; set; }
        public string num_fact { get; set; }
        public string operacion { get; set; }
        public string fecha_operacion { get; set; }
        public string tupa_serv { get; set; }
        public Nullable<int> cantidad { get; set; }
    }
}
