//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGESDOC.Response
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConsultaSolicitudInspeccionOdResponse
    {
        public int id_sol_ins { get; set; }
        public Nullable<int> id_estado { get; set; }
        public Nullable<System.DateTime> fecha_crea { get; set; }
        public string fecha_crea_text { get; set; }
        public string externo { get; set; }
        public string nombre_estado { get; set; }
        public string nombre_tipo_solicitud { get; set; }
        public string solicitud_inspeccion { get; set; }
        public Nullable<int> id_od_insp { get; set; }
        public string persona_contacto { get; set; }
        public string telefono_oficina { get; set; }
        public string telefono_planta { get; set; }
        public string correo { get; set; }
        public string resolucion { get; set; }
        public string observaciones { get; set; }
        public string expediente { get; set; }
        public Nullable<int> id_seguimiento { get; set; }
        public string nombre_externo { get; set; }
        public string inspector { get; set; }
        public Nullable<System.DateTime> fecha_inspeccion { get; set; }
        public Nullable<System.DateTime> fecha_recepcion_inspector { get; set; }
        public string nom_inspector { get; set; }
        public string fecha_inspeccion_text { get; set; }
        public string fecha_recepcion_inspector_text { get; set; }
    }
}
