//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGESDOC.Response
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConsultarPlantasResponse
    {
        public int id_planta { get; set; }
        public Nullable<int> id_sede_oficina { get; set; }
        public Nullable<int> id_tipo_planta { get; set; }
        public Nullable<int> numero_planta { get; set; }
        public string nombre_planta { get; set; }
        public Nullable<System.DateTime> fecha_registro { get; set; }
        public string usuario_registro { get; set; }
        public Nullable<System.DateTime> fecha_modificacion { get; set; }
        public string usuario_modificacion { get; set; }
        public Nullable<int> id_tipo_actividad { get; set; }
        public Nullable<int> id_filial { get; set; }
        public string activo { get; set; }
        public Nullable<System.DateTime> fecha_habilitacion_final { get; set; }
        public Nullable<int> ind_habilitacion { get; set; }
    }
}
