//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGESDOC.Response
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConsultaEmbarcacionesResponse
    {
        public int id_embarcacion { get; set; }
        public string matricula { get; set; }
        public string nombre { get; set; }
        public Nullable<int> id_tipo_embarcacion { get; set; }
        public Nullable<System.DateTime> fecha_registro { get; set; }
        public string usuario_registro { get; set; }
        public Nullable<System.DateTime> fecha_modificacion { get; set; }
        public string usuario_modificacion { get; set; }
        public string activo { get; set; }
        public Nullable<int> codigo_habilitacion { get; set; }
        public Nullable<int> num_cod_habilitacion { get; set; }
        public string nom_cod_habilitacion { get; set; }
        public Nullable<int> id_tipo_act_emb { get; set; }
        public Nullable<System.DateTime> fecha_construccion { get; set; }
    }
}
