//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGESDOC.Response
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConsultarDbGeneralMaeZonaProduccionResponse
    {
        public int id_zona_produccion { get; set; }
        public string activo { get; set; }
        public string union_europea { get; set; }
        public string cod_union_europea { get; set; }
        public string ubigeo { get; set; }
        public string departamento { get; set; }
        public string provincia { get; set; }
        public string distrito { get; set; }
        public string cod_zona_produccion { get; set; }
        public string nombre { get; set; }
    }
}
