//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGESDOC.Response
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConsultarDbGeneralMaeAreaProduccionResponse
    {
        public int id_area_produccion { get; set; }
        public Nullable<int> id_zona_produccion { get; set; }
        public Nullable<int> id_estado_area_pro { get; set; }
        public Nullable<int> id_tipo_area_pro { get; set; }
        public string estado { get; set; }
        public string cod_zona_produccion { get; set; }
        public string union_europea { get; set; }
        public string cod_union_europea { get; set; }
        public string cod_area_produccion { get; set; }
        public string nombre { get; set; }
        public string tipo_area { get; set; }
    }
}
