//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGESDOC.Response
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConsultaPendientesSanipesDetalleResponse
    {
        public string hoja_tramite { get; set; }
        public System.DateTime fecha_emision { get; set; }
        public Nullable<int> tupa { get; set; }
        public string asunto_tupa { get; set; }
        public string estado { get; set; }
        public System.DateTime fecha_envio { get; set; }
        public Nullable<System.DateTime> fecha_recepcion { get; set; }
        public string oficina { get; set; }
        public string asunto { get; set; }
        public string destino { get; set; }
        public string persona_envia { get; set; }
    }
}
