//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGESDOC.Response
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConsultarUsuarioResponse
    {
        public string ruc { get; set; }
        public string persona_num_documento { get; set; }
        public int id_perfil { get; set; }
        public string empresa { get; set; }
        public string razon_social { get; set; }
        public string persona { get; set; }
        public string perfil { get; set; }
        public int id_oficina_direccion { get; set; }
        public int id_oficina { get; set; }
        public string nom_ofi { get; set; }
        public int id_sede { get; set; }
        public string nom_sede { get; set; }
        public Nullable<int> id_perfil_jefe_od { get; set; }
        public Nullable<int> id_perfil_inspector_od { get; set; }
    }
}
