//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGESDOC.Response
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConsultaDbGeneralMaeFacturaResponse
    {
        public int id_factura { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string fecha_text { get; set; }
        public string comprobante { get; set; }
        public string importe { get; set; }
        public string tupa_serv { get; set; }
        public string valor_fact_exp { get; set; }
        public string documento { get; set; }
        public string externo { get; set; }
        public string direccion { get; set; }
        public string operaciones { get; set; }
        public string tipo_factura { get; set; }
        public string usuario_registro { get; set; }
        public string ruta_pdf { get; set; }
        public Nullable<int> id_operacion { get; set; }
    }
}
