//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGESDOC.Response
{
    using System;
    using System.Collections.Generic;
    
    public partial class DbGeneralMaeCodigoDesembarcaderoResponse
    {
        public int id_cod_desemb { get; set; }
        public string codigo { get; set; }
        public Nullable<int> id_tipo_desembarcadero { get; set; }
        public string activo { get; set; }
    }
}
