//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGESDOC.Response
{
    using System;
    using System.Collections.Generic;

    public partial class DbGeneralMaeDesembarcaderoResponse
    {
        public string ruta_pdf { get; set; }

        public string genera_data_tipo_desembarcadero { get; set; }
        public string genera_data_codigo_desembarcadero { get; set; }
        public string genera_data_denominacion { get; set; }
        public string genera_data_externo { get; set; }
        public string genera_data_direccion { get; set; }
        public string genera_data_pesca_acuicultura { get; set; }
        public string genera_data_archivos { get; set; }

    }
}
