//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGESDOC.Response
{
    using System;
    using System.Collections.Generic;
    
    public partial class DbGeneralMaeDesembarcaderoResponse
    {
        public int id_desembarcadero { get; set; }
        public Nullable<int> id_sede { get; set; }
        public Nullable<int> id_tipo_desembarcadero { get; set; }
        public string entidad { get; set; }
        public string nombre_tipo_desembarcadero { get; set; }
        public string denominacion { get; set; }
        public Nullable<double> latitud { get; set; }
        public Nullable<double> longitud { get; set; }
        public string codigo_desembarcadero { get; set; }
        public string estado_desemb { get; set; }
    }
}
