//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGESDOC.Response
{
    using System;
    using System.Collections.Generic;

    public partial class DbGeneralMaeTransporteResponse
    {
        public string genera_data_externo { get; set; }
        public string genera_data_Placa { get; set; }
        public string genera_data_cod_Habilitacion { get; set; }
        public string genera_data_protocolo { get; set; }
        public string genera_data_fecha { get; set; }
        public string genera_data_fecha_id { get; set; }
        public string genera_data_ruta { get; set; }
        public string genera_data_pdf { get; set; }
    }
}