//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SIGESDOC.Response
{
    using System;
    using System.Collections.Generic;

    public partial class DbProtocoloAntiguoHabPlantaListarResponse
    {
        public virtual DbProtocoloAntiguoHabEmpresaListarResponse Db_Protocolo_Antiguo_Hab_Empresa_Listar { get; set; }
        public virtual List<DbProtocoloAntiguoHabPlantaProtocoloListarResponse> Db_Protocolo_Antiguo_Hab_Planta_Protocolo_Listar { get; set; }  
        
    }
}
