//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGESDOC.Response
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocDetObservacionesResponse
    {
        public int id_det_doc_observacion { get; set; }
        public Nullable<int> id_det_documento { get; set; }
        public string observacion { get; set; }
        public string usuario_crea { get; set; }
        public Nullable<System.DateTime> fecha_crea { get; set; }
        public string activo { get; set; }
    
        public virtual DocumentoDetalleResponse documento_detalle { get; set; }
    }
}
