//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGESDOC.Response
{
    using System;
    using System.Collections.Generic;

    public partial class DocumentoResponse
    {
        public string siglas_oficina { get; set; }
        public string documento_completo { get; set; }
        public string fecha_texto_corto { get; set; }

    }
}