//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGESDOC.Response
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentoDhcpaDetalleResponse
    {
        public int id_doc_dhcpa_det { get; set; }
        public Nullable<int> id_doc_dhcpa { get; set; }
        public Nullable<int> id_oficina_direccion_destino { get; set; }
        public string persona_destino { get; set; }
        public string activo { get; set; }
        public string usuario_registro { get; set; }
        public Nullable<System.DateTime> fecha_registro { get; set; }
        public string usuario_modifica { get; set; }
        public Nullable<System.DateTime> fecha_modifica { get; set; }
        public string nombre_persona_destino { get; set; }
    
        public virtual DocumentoDhcpaResponse documento_dhcpa { get; set; }
    }
}
