//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGESDOC.Response
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentoSeguimientoResponse
    {
        public int id_documento_seg { get; set; }
        public byte id_tipo_documento { get; set; }
        public Nullable<int> num_documento { get; set; }
        public string nom_documento { get; set; }
        public string asunto { get; set; }
        public Nullable<System.DateTime> fecha_documento { get; set; }
        public Nullable<System.DateTime> fecha_crea { get; set; }
        public string usuario_crea { get; set; }
        public Nullable<int> oficina_crea { get; set; }
        public Nullable<System.DateTime> fecha_recepcion_sdhpa { get; set; }
        public string usuario_recepcion_sdhpa { get; set; }
        public Nullable<System.DateTime> fecha_asignacion_evaluador { get; set; }
        public string evaluador { get; set; }
        public Nullable<System.DateTime> fecha_recibido_evaluador { get; set; }
        public string estado { get; set; }
        public string indicador { get; set; }
        public Nullable<int> id_servicio_dhcpa { get; set; }
        public Nullable<System.DateTime> fecha_od { get; set; }
        public string usuario_od { get; set; }
        public string expedientes_relacion { get; set; }
        public string ruta_pdf { get; set; }
        public string archivo_pdf { get; set; }
        public Nullable<int> folios { get; set; }
        public string nom_ofi_crea { get; set; }
    
        public virtual List<DetDocFactResponse> det_doc_fact { get; set; }
        public virtual List<DetSegDocResponse> det_seg_doc { get; set; }
        public virtual TipoDocumentoResponse tipo_documento { get; set; }
        public virtual List<DocumentoSeguimientoAdjuntoResponse> documento_seguimiento_adjunto { get; set; }
    }
}
