//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGESDOC.Response
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentoSeguimientoAdjuntoResponse
    {
        public int id_doc_seg_adjunto { get; set; }
        public Nullable<int> id_documento_seg { get; set; }
        public Nullable<int> id_tipo_doc_seg_adjunto { get; set; }
        public string usuario_crea { get; set; }
        public Nullable<System.DateTime> fecha_crea { get; set; }
        public string activo { get; set; }
    
        public virtual DocumentoSeguimientoResponse documento_seguimiento { get; set; }
        public virtual TipoDocumentoSeguimientoAdjuntoResponse tipo_documento_seguimiento_adjunto { get; set; }
    }
}
