//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGESDOC.Response
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentoDhcpaResponse
    {
        public int id_doc_dhcpa { get; set; }
        public Nullable<int> id_tipo_documento { get; set; }
        public int num_doc { get; set; }
        public string nom_doc { get; set; }
        public Nullable<System.DateTime> fecha_doc { get; set; }
        public string asunto { get; set; }
        public string anexos { get; set; }
        public Nullable<System.DateTime> fecha_registro { get; set; }
        public string usuario_registro { get; set; }
        public Nullable<int> id_archivador { get; set; }
        public Nullable<int> id_filial { get; set; }
        public Nullable<int> numero_ht { get; set; }
        public string pdf { get; set; }
    
        public virtual List<DetSegDocDhcpaResponse> det_seg_doc_dhcpa { get; set; }
        public virtual List<DocumentoDhcpaDetalleResponse> documento_dhcpa_detalle { get; set; }
    }
}
