
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGESDOC.Response
{
    using System;
    using System.Collections.Generic;

    public partial class DocumentoDhcpaResponse
    {
        public string nom_tipo_documento { get; set; }
        public string lugar_destino { get; set; }
        public string persona_destino { get; set; }
        public string nom_filial { get; set; }
        public string fecha_doc_text { get; set; }
    }
}
