//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGESDOC.Response
{
    using System;
    using System.Collections.Generic;

    public partial class DocumentoSeguimientoResponse
    {
        public string nom_externo { get; set; }
        public string nom_tipo_documento { get; set; }
        public string fecha_documento_text { get; set; }
        public string fecha_crea_text { get; set; }
        public string group_expedientes { get; set; }
        public string documento_codigo_habilitacion { get; set; }
        public string usu_crea { get; set; }

    }
}