//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGESDOC.Response
{
    using System;
    using System.Collections.Generic;

    public partial class EspeciesHabilitacionesResponse
    {
        public string nombre_comun { get; set; }
        public string nombre_cientifico { get; set; }
        public string especie_categoria { get; set; }

    }
}