//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGESDOC.Response
{
    using System;
    using System.Collections.Generic;
    
    public partial class EspeciesHabilitacionesResponse
    {
        public int id_det_espec_hab { get; set; }
        public string codigo_especie { get; set; }
        public string activo { get; set; }
    
        public virtual List<ProtocoloEspecieResponse> protocolo_especie { get; set; }
    }
}
