//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGESDOC.Response
{
    using System;
    using System.Collections.Generic;
    
    public partial class EstadoTramiteResponse
    {
        public byte id_est_tramite { get; set; }
        public string nombre { get; set; }
    
        public virtual List<DocumentoDetalleResponse> documento_detalle { get; set; }
        public virtual List<LogDesarchivoDesatendidoResponse> log_desarchivo_desatendido { get; set; }
    }
}
