//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGESDOC.Response
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExpedienteUnicoResponse
    {
        public int id_expediente { get; set; }
        public Nullable<int> año { get; set; }
        public string fuente_sistema { get; set; }
        public Nullable<System.DateTime> fecharegistro { get; set; }
        public string observacion { get; set; }
        public Nullable<int> estado { get; set; }
    }
}
