//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGESDOC.Response
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExpedienteUnicoResponse
    {
        public int id_expediente { get; set; }
        public Nullable<int> año { get; set; }
        public string fuente_sistema { get; set; }
        public Nullable<System.DateTime> fecharegistro { get; set; }
        public string observacion { get; set; }
        public Nullable<int> estado { get; set; }
    }
}
