//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGESDOC.Response
{
    using System;
    using System.Collections.Generic;

    public partial class HojaTramiteResponse
    {
        public string nombre_tipo_documento { get; set; }
        public string nombre_oficina { get; set; }
        public string nombre_tipo_tramite { get; set; }
        public string fecha_emision_text { get; set; }
        public bool ver_pdf { get; set; }
        public bool ver_editar { get; set; }
        public string siga_asunto { get; set; }
        public string siga_centro_costo { get; set; }
        public string nom_tupa { get; set; }
        public string nom_estado { get; set; }
    }
}