//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGESDOC.Response
{
    using System;
    using System.Collections.Generic;
    
    public partial class InformeTecnicoEvalResponse
    {
        public int id_inf_tec_eval { get; set; }
        public int numero_documento { get; set; }
        public Nullable<int> id_seguimiento { get; set; }
        public string observaciones { get; set; }
        public Nullable<System.DateTime> fecha_crea { get; set; }
        public Nullable<int> oficina_crea { get; set; }
        public string usuario_crea { get; set; }
        public Nullable<int> año_crea { get; set; }
    
        public virtual SeguimientoDhcpaResponse seguimiento_dhcpa { get; set; }
    }
}
