//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGESDOC.Response
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogDesarchivoDesatendidoResponse
    {
        public int id_log_des_ar_at { get; set; }
        public Nullable<int> id_det_documento { get; set; }
        public Nullable<byte> old_id_est_tramite { get; set; }
        public Nullable<System.DateTime> old_fecha { get; set; }
        public string old_usuario { get; set; }
        public string old_observacion { get; set; }
        public Nullable<System.DateTime> fecha_desactivo { get; set; }
        public string usuario_desactivo { get; set; }
        public string observacion { get; set; }
    
        public virtual DocumentoDetalleResponse documento_detalle { get; set; }
        public virtual EstadoTramiteResponse estado_tramite { get; set; }
    }
}
