//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGESDOC.Response
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProtocoloTransporteResponse
    {
        public int id_dat_pro_transporte { get; set; }
        public Nullable<int> id_protocolo { get; set; }
        public Nullable<int> numero { get; set; }
        public Nullable<int> anno { get; set; }
        public Nullable<int> direccion_legal { get; set; }
        public Nullable<int> representante_legal { get; set; }
        public Nullable<int> id_tipo_camara_trans { get; set; }
        public Nullable<int> id_transporte { get; set; }
        public string placa { get; set; }
        public string cod_habilitacion { get; set; }
        public Nullable<int> id_tipo_carroceria { get; set; }
        public Nullable<int> id_um { get; set; }
        public Nullable<decimal> carga_util { get; set; }
        public string acta_inspeccion { get; set; }
        public string informe_auditoria { get; set; }
        public string informe_tecnico_evaluacion { get; set; }
        public string persona_2 { get; set; }
        public string direccion_legal_dni { get; set; }
        public Nullable<int> representante_legal_dni { get; set; }
        public Nullable<int> id_tipo_furgon { get; set; }
        public Nullable<int> id_tipo_carroceria_tarpro { get; set; }
        public Nullable<int> id_tipo_atencion { get; set; }
        public string informe_sdhpa { get; set; }
    
        public virtual ProtocoloResponse protocolo { get; set; }
    }
}
