//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGESDOC.Response
{
    using System;
    using System.Collections.Generic;

    public partial class ProtocoloAutorizacionInstalacionResponse
    {
        public string genera_data_protocolo { get; set; }
        public string genera_data_fecha { get; set; }
        public string genera_data_fecha_id { get; set; }
        public string genera_data_proposito { get; set; }
        public string genera_data_establecimiento { get; set; }
        public string genera_data_actividad { get; set; }
        public string genera_data_ubicacion { get; set; }
        public string genera_data_departamento { get; set; }
        public string genera_data_provincia { get; set; }
        public string genera_data_distrito { get; set; }
        public string genera_data_ruta { get; set; }
        public string genera_data_pdf { get; set; }
        public Nullable<int> genera_data_annio { get; set; }
    }
}

