//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGESDOC.Response
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProtocoloPlantaResponse
    {
        public int id_dat_pro_pla { get; set; }
        public Nullable<int> id_protocolo { get; set; }
        public Nullable<int> direccion_legal { get; set; }
        public Nullable<int> representante_legal { get; set; }
        public string licencia_operacion { get; set; }
        public string ind_concha_abanico { get; set; }
        public string ind_otros { get; set; }
        public string ind_peces { get; set; }
        public string ind_crustaceos { get; set; }
        public Nullable<int> id_tipo_ch { get; set; }
        public string activo { get; set; }
    
        public virtual ProtocoloResponse protocolo { get; set; }
        public virtual TipoConsumoHumanoResponse tipo_consumo_humano { get; set; }
    }
}
