//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGESDOC.Response
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoExpedienteResponse
    {
        public int id_tipo_expediente { get; set; }
        public string nombre { get; set; }
        public Nullable<int> id_oficina_dir { get; set; }
        public Nullable<int> id_tupa { get; set; }
    
        public virtual List<ExpedientesResponse> expedientes { get; set; }
    }
}
