//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGESDOC.Response
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoDocumentoResponse
    {
        public byte id_tipo_documento { get; set; }
        public string nombre { get; set; }
        public string tp_e_i { get; set; }
    
        public virtual List<DocumentoSeguimientoResponse> documento_seguimiento { get; set; }
        public virtual List<DocumentoResponse> documento { get; set; }
    }
}
