//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGESDOC.Response
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoDocumentoSeguimientoAdjuntoResponse
    {
        public int id_tipo_doc_seg_adjunto { get; set; }
        public string nombre { get; set; }
        public string activo { get; set; }
        public Nullable<int> id_tipo_seguimiento { get; set; }
    
        public virtual List<DocumentoSeguimientoAdjuntoResponse> documento_seguimiento_adjunto { get; set; }
        public virtual TipoSeguimientoResponse tipo_seguimiento { get; set; }
    }
}
