//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGESDOC.Response
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoExpedienteResponse
    {
        public int id_tipo_expediente { get; set; }
        public string nombre { get; set; }
        public Nullable<int> id_oficina_dir { get; set; }
        public Nullable<int> id_tupa { get; set; }
    
        public virtual List<ExpedientesResponse> expedientes { get; set; }
    }
}
