//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGESDOC.Response
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoDocumentoResponse
    {
        public byte id_tipo_documento { get; set; }
        public string nombre { get; set; }
        public string tp_e_i { get; set; }
    
        public virtual List<DocumentoSeguimientoResponse> documento_seguimiento { get; set; }
        public virtual List<DocumentoResponse> documento { get; set; }
    }
}
