//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGESDOC.Response
{
    using System;
    using System.Collections.Generic;
    
    public partial class TupaResponse
    {
        public int id_tupa { get; set; }
        public Nullable<int> numero { get; set; }
        public Nullable<int> id_tipo_procedimiento { get; set; }
        public string asunto { get; set; }
        public string activo { get; set; }
        public Nullable<int> dias_tupa { get; set; }
        public Nullable<int> id_tipo_tupa { get; set; }
        public Nullable<int> id_oficina { get; set; }
        public Nullable<int> prorroga_dias { get; set; }
        public Nullable<double> costo { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public Nullable<System.DateTime> fecha_caducacion { get; set; }
        public Nullable<int> anio_servicio { get; set; }
    
        public virtual List<SubTupaResponse> sub_tupa { get; set; }
        public virtual TipoProcedimientoResponse tipo_procedimiento { get; set; }
        public virtual TipoTupaResponse tipo_tupa { get; set; }
    }
}
