//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGESDOC.Response
{
    using System;
    using System.Collections.Generic;
    
    public partial class VerPedientesGesdocResponse
    {
        public Nullable<int> anio { get; set; }
        public int id_oficina { get; set; }
        public Nullable<int> tupa { get; set; }
        public Nullable<int> cant { get; set; }
    }
}
