//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGESDOC.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Consultar_ptocolo_transporte_x_id_transporte_2018_v1
    {
        public string RAZON_SOCIAL { get; set; }
        public string DIRECCION_LEGAL { get; set; }
        public string REPRESENTANTE_LEGAL { get; set; }
        public string INFRA_PESQ { get; set; }
        public int ID_TRANSPORTE { get; set; }
        public string PLACA { get; set; }
        public string COD_HABILITACION { get; set; }
        public Nullable<int> ID_TIPO_CARROCERIA { get; set; }
        public string NOMBRE_CARROCERIA { get; set; }
        public Nullable<int> ID_UM { get; set; }
        public string NOMBRE_UM { get; set; }
        public string SIGLAS_UM { get; set; }
        public string CARGA_UTIL { get; set; }
        public string ESTADO { get; set; }
        public string NOMBRE_ESTADO { get; set; }
        public string ACTA_INSPECCION { get; set; }
        public string INFORME_AUDITORIA { get; set; }
        public string INFORME_TECNICO_EVALUACION { get; set; }
        public string FECHA_INICIO { get; set; }
        public string FECHA_FIN { get; set; }
        public string FECHA_EMISION { get; set; }
        public string NOMBRE_PROTOCOLO { get; set; }
        public string EXPEDIENTE { get; set; }
        public int ID_TIPO_FURGON { get; set; }
        public string NOMBRE_TIPO_FURGON { get; set; }
        public int ID_PROTOCOLO { get; set; }
        public string INFORME_SDHPA { get; set; }
    }
}
