//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGESDOC.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class COUNT_EXPEDIENTE_UNICO
    {
        public int ID_EXPEDIENTE { get; set; }
        public Nullable<int> AÑO { get; set; }
        public string FUENTE_SISTEMA { get; set; }
        public Nullable<System.DateTime> fechaRegistro { get; set; }
        public string observacion { get; set; }
        public Nullable<int> estado { get; set; }
    }
}
