//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGESDOC.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class COUNT_EXPEDIENTE_UNICO
    {
        public int ID_EXPEDIENTE { get; set; }
        public Nullable<int> AÑO { get; set; }
        public string FUENTE_SISTEMA { get; set; }
        public Nullable<System.DateTime> fechaRegistro { get; set; }
        public string observacion { get; set; }
        public Nullable<int> estado { get; set; }
    }
}
