//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGESDOC.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class DAT_DOC_DET_OBSERVACIONES
    {
        public int ID_DET_DOC_OBSERVACION { get; set; }
        public Nullable<int> ID_DET_DOCUMENTO { get; set; }
        public string OBSERVACION { get; set; }
        public string USUARIO_CREA { get; set; }
        public Nullable<System.DateTime> FECHA_CREA { get; set; }
        public string ACTIVO { get; set; }
    
        public virtual DAT_DOCUMENTO_DETALLE DAT_DOCUMENTO_DETALLE { get; set; }
    }
}
