//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGESDOC.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class DAT_PROTOCOLO_LICENCIA_OPERACION
    {
        public int ID_PRO_LICENCIA_OPERACION { get; set; }
        public Nullable<int> ID_PROTOCOLO { get; set; }
        public string RESOLUCION_AUTORIZACION_INSTALACION { get; set; }
        public Nullable<System.DateTime> FECHA_RESOLUCION { get; set; }
        public string RUC { get; set; }
        public Nullable<int> ID_SEDE { get; set; }
        public Nullable<int> ID_REPRESENTANTE_LEGAL { get; set; }
        public Nullable<int> ID_TIPO_LICENCIA_OPERACION { get; set; }
        public string ACTIVIDAD { get; set; }
    
        public virtual MAE_PROTOCOLO MAE_PROTOCOLO { get; set; }
        public virtual MAE_TIPO_LICENCIA_OPERACION MAE_TIPO_LICENCIA_OPERACION { get; set; }
    }
}
