//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGESDOC.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class DAT_PROTOCOLO_ALMACEN
    {
        public int ID_DAT_PRO_ALMACEN { get; set; }
        public Nullable<int> ID_PROTOCOLO { get; set; }
        public Nullable<int> DIRECCION_LEGAL { get; set; }
        public Nullable<int> REPRESENTANTE_LEGAL { get; set; }
        public string LICENCIA { get; set; }
        public Nullable<int> ID_TIPO_CH { get; set; }
    
        public virtual MAE_PROTOCOLO MAE_PROTOCOLO { get; set; }
        public virtual MAE_TIPO_CONSUMO_HUMANO MAE_TIPO_CONSUMO_HUMANO { get; set; }
    }
}
