//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGESDOC.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class DAT_PROTOCOLO_ESPECIE
    {
        public int ID_PRO_ESPE { get; set; }
        public Nullable<int> ID_PROTOCOLO { get; set; }
        public Nullable<int> ID_DET_ESPEC_HAB { get; set; }
        public string ACTIVO { get; set; }
    
        public virtual DAT_ESPECIES_HABILITACIONES DAT_ESPECIES_HABILITACIONES { get; set; }
        public virtual MAE_PROTOCOLO MAE_PROTOCOLO { get; set; }
    }
}
