//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGESDOC.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class DAT_DET_SEG_DOC
    {
        public int ID_DET_DOC { get; set; }
        public int ID_DOCUMENTO_SEG { get; set; }
        public int ID_SEGUIMIENTO { get; set; }
        public string ACTIVO { get; set; }
    
        public virtual MAE_DOCUMENTO_SEGUIMIENTO MAE_DOCUMENTO_SEGUIMIENTO { get; set; }
        public virtual MAE_SEGUIMIENTO_DHCPA MAE_SEGUIMIENTO_DHCPA { get; set; }
    }
}
