//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGESDOC.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class DAT_DOCUMENTO_DHCPA_DETALLE
    {
        public int ID_DOC_DHCPA_DET { get; set; }
        public Nullable<int> ID_DOC_DHCPA { get; set; }
        public Nullable<int> ID_OFICINA_DIRECCION_DESTINO { get; set; }
        public string PERSONA_DESTINO { get; set; }
        public string ACTIVO { get; set; }
        public string USUARIO_REGISTRO { get; set; }
        public Nullable<System.DateTime> FECHA_REGISTRO { get; set; }
        public string USUARIO_MODIFICA { get; set; }
        public Nullable<System.DateTime> FECHA_MODIFICA { get; set; }
        public string NOMBRE_PERSONA_DESTINO { get; set; }
        public Nullable<bool> FLAG_TIPO_CARTA { get; set; }
    
        public virtual MAE_DOCUMENTO_DHCPA MAE_DOCUMENTO_DHCPA { get; set; }
    }
}
