//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGESDOC.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class DAT_DET_SEG_EVALUADOR
    {
        public int ID_DET_EXP_EVA { get; set; }
        public Nullable<int> ID_SEGUIMIENTO { get; set; }
        public string EVALUADOR { get; set; }
        public string INDICADOR { get; set; }
        public Nullable<System.DateTime> FECHA_RECIBIDO { get; set; }
        public Nullable<System.DateTime> FECHA_DERIVADO { get; set; }
    
        public virtual MAE_SEGUIMIENTO_DHCPA MAE_SEGUIMIENTO_DHCPA { get; set; }
    }
}
