//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGESDOC.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAE_TIPO_EXPEDIENTE
    {
        public MAE_TIPO_EXPEDIENTE()
        {
            this.MAE_EXPEDIENTES = new HashSet<MAE_EXPEDIENTES>();
        }
    
        public int ID_TIPO_EXPEDIENTE { get; set; }
        public string NOMBRE { get; set; }
        public Nullable<int> ID_OFICINA_DIR { get; set; }
        public Nullable<int> ID_TUPA { get; set; }
    
        public virtual ICollection<MAE_EXPEDIENTES> MAE_EXPEDIENTES { get; set; }
    }
}
