//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGESDOC.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAE_SUB_TUPA
    {
        public int ID_SUB_TUPA { get; set; }
        public Nullable<int> ID_TUPA { get; set; }
        public string INDICE { get; set; }
        public string NOMBRE { get; set; }
        public Nullable<decimal> PRECIO { get; set; }
        public string ACTIVO { get; set; }
        public Nullable<int> INDICADOR { get; set; }
    
        public virtual MAE_TUPA MAE_TUPA { get; set; }
    }
}
