//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGESDOC.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAE_SEGUIMIENTO_DHCPA
    {
        public MAE_SEGUIMIENTO_DHCPA()
        {
            this.DAT_DET_SEG_DOC = new HashSet<DAT_DET_SEG_DOC>();
            this.DAT_DET_SEG_DOC_DHCPA = new HashSet<DAT_DET_SEG_DOC_DHCPA>();
            this.DAT_DET_SEG_EVALUADOR = new HashSet<DAT_DET_SEG_EVALUADOR>();
            this.MAE_CONSTANCIA_HACCP = new HashSet<MAE_CONSTANCIA_HACCP>();
            this.MAE_INFORME_TECNICO_EVAL = new HashSet<MAE_INFORME_TECNICO_EVAL>();
            this.MAE_PROTOCOLO = new HashSet<MAE_PROTOCOLO>();
            this.MAE_SEGUIMIENTO_DHCPA_OBSERVACIONES = new HashSet<MAE_SEGUIMIENTO_DHCPA_OBSERVACIONES>();
            this.MAE_SOLICITUD_INSPECCION = new HashSet<MAE_SOLICITUD_INSPECCION>();
        }
    
        public int ID_SEGUIMIENTO { get; set; }
        public Nullable<int> ID_EXPEDIENTE { get; set; }
        public Nullable<int> TUPA { get; set; }
        public Nullable<int> ID_TIPO_PROCEDIMIENTO { get; set; }
        public System.DateTime FECHA_INICIO { get; set; }
        public Nullable<System.DateTime> FECHA_FIN { get; set; }
        public Nullable<int> ID_OFI_DIR { get; set; }
        public string PERSONA_NUM_DOCUMENTO { get; set; }
        public string EVALUADOR { get; set; }
        public Nullable<int> ID_EMBARCACION { get; set; }
        public Nullable<int> ID_PLANTA { get; set; }
        public Nullable<int> OFICINA_CREA { get; set; }
        public string PERSONA_CREA { get; set; }
        public string ESTADO { get; set; }
        public Nullable<int> DURACION_TRAMITE { get; set; }
        public Nullable<int> DURACION_SDHPA { get; set; }
        public string OBSERVACIONES { get; set; }
        public string INSPECTO_DESIGNADO { get; set; }
        public Nullable<System.DateTime> FECHA_AUDITORIA { get; set; }
        public Nullable<System.DateTime> FECHA_ENVIO_ACTA { get; set; }
        public Nullable<System.DateTime> FECHA_ENVIO_OFICIO_SDHPA { get; set; }
        public string CON_PROCESO { get; set; }
        public Nullable<int> ID_TIPO_SEGUIMIENTO { get; set; }
        public Nullable<int> ID_HABILITANTE { get; set; }
        public string COD_HABILITANTE { get; set; }
        public string NOM_OFICINA_CREA { get; set; }
        public string NOMBRE_EXTERNO { get; set; }
    
        public virtual ICollection<DAT_DET_SEG_DOC> DAT_DET_SEG_DOC { get; set; }
        public virtual ICollection<DAT_DET_SEG_DOC_DHCPA> DAT_DET_SEG_DOC_DHCPA { get; set; }
        public virtual ICollection<DAT_DET_SEG_EVALUADOR> DAT_DET_SEG_EVALUADOR { get; set; }
        public virtual ICollection<MAE_CONSTANCIA_HACCP> MAE_CONSTANCIA_HACCP { get; set; }
        public virtual ICollection<MAE_INFORME_TECNICO_EVAL> MAE_INFORME_TECNICO_EVAL { get; set; }
        public virtual ICollection<MAE_PROTOCOLO> MAE_PROTOCOLO { get; set; }
        public virtual ICollection<MAE_SEGUIMIENTO_DHCPA_OBSERVACIONES> MAE_SEGUIMIENTO_DHCPA_OBSERVACIONES { get; set; }
        public virtual ICollection<MAE_SOLICITUD_INSPECCION> MAE_SOLICITUD_INSPECCION { get; set; }
    }
}
