//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGESDOC.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAE_TIPO_PROCEDIMIENTO
    {
        public MAE_TIPO_PROCEDIMIENTO()
        {
            this.MAE_TUPA = new HashSet<MAE_TUPA>();
        }
    
        public int ID_TIPO_PROCEDIMIENTO { get; set; }
        public string NOMBRE { get; set; }
    
        public virtual ICollection<MAE_TUPA> MAE_TUPA { get; set; }
    }
}
