//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGESDOC.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAE_TIPO_CAMARA_TRANSPORTE
    {
        public int ID_TIPO_CAMARA_TRANS { get; set; }
        public string NOMBRE { get; set; }
        public string ACTIVO { get; set; }
    }
}
