//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGESDOC.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAE_TIPO_CONSUMO_HUMANO
    {
        public MAE_TIPO_CONSUMO_HUMANO()
        {
            this.DAT_PROTOCOLO_ALMACEN = new HashSet<DAT_PROTOCOLO_ALMACEN>();
            this.DAT_PROTOCOLO_PLANTA = new HashSet<DAT_PROTOCOLO_PLANTA>();
            this.MAE_PROTOCOLO = new HashSet<MAE_PROTOCOLO>();
        }
    
        public int ID_TIPO_CH { get; set; }
        public string SIGLAS { get; set; }
        public string NOMBRE { get; set; }
    
        public virtual ICollection<DAT_PROTOCOLO_ALMACEN> DAT_PROTOCOLO_ALMACEN { get; set; }
        public virtual ICollection<DAT_PROTOCOLO_PLANTA> DAT_PROTOCOLO_PLANTA { get; set; }
        public virtual ICollection<MAE_PROTOCOLO> MAE_PROTOCOLO { get; set; }
    }
}
