//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGESDOC.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAE_TIPO_TRAMITE
    {
        public MAE_TIPO_TRAMITE()
        {
            this.MAE_HOJA_TRAMITE = new HashSet<MAE_HOJA_TRAMITE>();
        }
    
        public byte ID_TIPO_TRAMITE { get; set; }
        public string NOMBRE { get; set; }
    
        public virtual ICollection<MAE_HOJA_TRAMITE> MAE_HOJA_TRAMITE { get; set; }
    }
}
