//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGESDOC.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAE_SUB_TUPA
    {
        public int ID_SUB_TUPA { get; set; }
        public Nullable<int> ID_TUPA { get; set; }
        public string INDICE { get; set; }
        public string NOMBRE { get; set; }
        public Nullable<decimal> PRECIO { get; set; }
        public string ACTIVO { get; set; }
        public Nullable<int> INDICADOR { get; set; }
    
        public virtual MAE_TUPA MAE_TUPA { get; set; }
    }
}
