//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGESDOC.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAE_TIPO_TRAMITE
    {
        public MAE_TIPO_TRAMITE()
        {
            this.MAE_HOJA_TRAMITE = new HashSet<MAE_HOJA_TRAMITE>();
        }
    
        public byte ID_TIPO_TRAMITE { get; set; }
        public string NOMBRE { get; set; }
    
        public virtual ICollection<MAE_HOJA_TRAMITE> MAE_HOJA_TRAMITE { get; set; }
    }
}
