//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGESDOC.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAE_ESTADO_TRAMITE
    {
        public MAE_ESTADO_TRAMITE()
        {
            this.DAT_DOCUMENTO_DETALLE = new HashSet<DAT_DOCUMENTO_DETALLE>();
            this.DAT_LOG_DESARCHIVO_DESATENDIDO = new HashSet<DAT_LOG_DESARCHIVO_DESATENDIDO>();
        }
    
        public byte ID_EST_TRAMITE { get; set; }
        public string NOMBRE { get; set; }
    
        public virtual ICollection<DAT_DOCUMENTO_DETALLE> DAT_DOCUMENTO_DETALLE { get; set; }
        public virtual ICollection<DAT_LOG_DESARCHIVO_DESATENDIDO> DAT_LOG_DESARCHIVO_DESATENDIDO { get; set; }
    }
}
