//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGESDOC.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAE_DOCUMENTO_SEGUIMIENTO
    {
        public MAE_DOCUMENTO_SEGUIMIENTO()
        {
            this.DAT_DET_DOC_FACT = new HashSet<DAT_DET_DOC_FACT>();
            this.DAT_DET_SEG_DOC = new HashSet<DAT_DET_SEG_DOC>();
            this.MAE_DOCUMENTO_SEGUIMIENTO_ADJUNTO = new HashSet<MAE_DOCUMENTO_SEGUIMIENTO_ADJUNTO>();
        }
    
        public int ID_DOCUMENTO_SEG { get; set; }
        public byte ID_TIPO_DOCUMENTO { get; set; }
        public Nullable<int> NUM_DOCUMENTO { get; set; }
        public string NOM_DOCUMENTO { get; set; }
        public string ASUNTO { get; set; }
        public Nullable<System.DateTime> FECHA_DOCUMENTO { get; set; }
        public Nullable<System.DateTime> FECHA_CREA { get; set; }
        public string USUARIO_CREA { get; set; }
        public Nullable<int> OFICINA_CREA { get; set; }
        public Nullable<System.DateTime> FECHA_RECEPCION_SDHPA { get; set; }
        public string USUARIO_RECEPCION_SDHPA { get; set; }
        public Nullable<System.DateTime> FECHA_ASIGNACION_EVALUADOR { get; set; }
        public string EVALUADOR { get; set; }
        public Nullable<System.DateTime> FECHA_RECIBIDO_EVALUADOR { get; set; }
        public string ESTADO { get; set; }
        public string INDICADOR { get; set; }
        public Nullable<int> ID_SERVICIO_DHCPA { get; set; }
        public Nullable<System.DateTime> FECHA_OD { get; set; }
        public string USUARIO_OD { get; set; }
        public string EXPEDIENTES_RELACION { get; set; }
        public string RUTA_PDF { get; set; }
        public string ARCHIVO_PDF { get; set; }
        public Nullable<int> FOLIOS { get; set; }
        public string NOM_OFI_CREA { get; set; }
    
        public virtual ICollection<DAT_DET_DOC_FACT> DAT_DET_DOC_FACT { get; set; }
        public virtual ICollection<DAT_DET_SEG_DOC> DAT_DET_SEG_DOC { get; set; }
        public virtual MAE_TIPO_DOCUMENTO MAE_TIPO_DOCUMENTO { get; set; }
        public virtual ICollection<MAE_DOCUMENTO_SEGUIMIENTO_ADJUNTO> MAE_DOCUMENTO_SEGUIMIENTO_ADJUNTO { get; set; }
    }
}
