//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGESDOC.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAE_TUPA
    {
        public MAE_TUPA()
        {
            this.MAE_SUB_TUPA = new HashSet<MAE_SUB_TUPA>();
        }
    
        public int ID_TUPA { get; set; }
        public Nullable<int> NUMERO { get; set; }
        public Nullable<int> ID_TIPO_PROCEDIMIENTO { get; set; }
        public string ASUNTO { get; set; }
        public string ACTIVO { get; set; }
        public Nullable<int> DIAS_TUPA { get; set; }
        public Nullable<int> ID_TIPO_TUPA { get; set; }
        public Nullable<int> ID_OFICINA { get; set; }
        public Nullable<int> PRORROGA_DIAS { get; set; }
        public Nullable<double> COSTO { get; set; }
        public Nullable<System.DateTime> FECHA_CREACION { get; set; }
        public Nullable<System.DateTime> FECHA_CADUCACION { get; set; }
        public Nullable<int> ANIO_SERVICIO { get; set; }
    
        public virtual ICollection<MAE_SUB_TUPA> MAE_SUB_TUPA { get; set; }
        public virtual MAE_TIPO_PROCEDIMIENTO MAE_TIPO_PROCEDIMIENTO { get; set; }
        public virtual MAE_TIPO_TUPA MAE_TIPO_TUPA { get; set; }
    }
}
