//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGESDOC.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAE_TIPO_EXPEDIENTE
    {
        public MAE_TIPO_EXPEDIENTE()
        {
            this.MAE_EXPEDIENTES = new HashSet<MAE_EXPEDIENTES>();
        }
    
        public int ID_TIPO_EXPEDIENTE { get; set; }
        public string NOMBRE { get; set; }
        public Nullable<int> ID_OFICINA_DIR { get; set; }
        public Nullable<int> ID_TUPA { get; set; }
    
        public virtual ICollection<MAE_EXPEDIENTES> MAE_EXPEDIENTES { get; set; }
    }
}
