//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGESDOC.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAE_TIPO_PROTOCOLO_EMBARCACION
    {
        public int ID_TIP_PRO_EMB { get; set; }
        public string NOMBRE { get; set; }
        public string ACTIVO { get; set; }
    }
}
