//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGESDOC.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAE_DOCUMENTO_SEGUIMIENTO_ADJUNTO
    {
        public int ID_DOC_SEG_ADJUNTO { get; set; }
        public Nullable<int> ID_DOCUMENTO_SEG { get; set; }
        public Nullable<int> ID_TIPO_DOC_SEG_ADJUNTO { get; set; }
        public string USUARIO_CREA { get; set; }
        public Nullable<System.DateTime> FECHA_CREA { get; set; }
        public string ACTIVO { get; set; }
    
        public virtual MAE_DOCUMENTO_SEGUIMIENTO MAE_DOCUMENTO_SEGUIMIENTO { get; set; }
        public virtual MAE_TIPO_DOCUMENTO_SEGUIMIENTO_ADJUNTO MAE_TIPO_DOCUMENTO_SEGUIMIENTO_ADJUNTO { get; set; }
    }
}
