//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGESDOC.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAE_REPORTE_COMPROBANTE_X_MES_CONSULTA
    {
        public int ID_COMPR_REPORT { get; set; }
        public string MES { get; set; }
        public string DIA_SEMANA { get; set; }
        public Nullable<int> DIA_NUM { get; set; }
        public Nullable<int> MES_NUM { get; set; }
        public Nullable<int> ANIO_NUM { get; set; }
        public Nullable<int> FECHA { get; set; }
        public Nullable<decimal> VENTA_CERT { get; set; }
        public string COMPR_CERT { get; set; }
        public Nullable<decimal> VENTA_PROT { get; set; }
        public string COMPR_PROT { get; set; }
        public Nullable<decimal> VENTA_ENSAYO { get; set; }
        public string COMPR_ENSAYO { get; set; }
        public Nullable<decimal> ACCESO_INFO { get; set; }
        public string COMPR_AINFO { get; set; }
        public Nullable<decimal> TOTAL { get; set; }
    }
}
