//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGESDOC.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAE_TIPO_DOCUMENTO
    {
        public MAE_TIPO_DOCUMENTO()
        {
            this.MAE_DOCUMENTO_SEGUIMIENTO = new HashSet<MAE_DOCUMENTO_SEGUIMIENTO>();
            this.MAE_DOCUMENTO = new HashSet<MAE_DOCUMENTO>();
        }
    
        public byte ID_TIPO_DOCUMENTO { get; set; }
        public string NOMBRE { get; set; }
        public string TP_E_I { get; set; }
    
        public virtual ICollection<MAE_DOCUMENTO_SEGUIMIENTO> MAE_DOCUMENTO_SEGUIMIENTO { get; set; }
        public virtual ICollection<MAE_DOCUMENTO> MAE_DOCUMENTO { get; set; }
    }
}
