//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGESDOC.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAE_ESTADOS_DEL_PROTOCOLO
    {
        public MAE_ESTADOS_DEL_PROTOCOLO()
        {
            this.MAE_ACTIVIDAD_PROTOCOLO = new HashSet<MAE_ACTIVIDAD_PROTOCOLO>();
        }
    
        public int ID_EST_PRO { get; set; }
        public string NOMBRE { get; set; }
        public string ACTIVO { get; set; }
    
        public virtual ICollection<MAE_ACTIVIDAD_PROTOCOLO> MAE_ACTIVIDAD_PROTOCOLO { get; set; }
    }
}
