//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGESDOC.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAE_VERSION_SOLICITUD
    {
        public MAE_VERSION_SOLICITUD()
        {
            this.MAE_SOLICITUD_INSPECCION = new HashSet<MAE_SOLICITUD_INSPECCION>();
        }
    
        public int ID_VERSION_SOL { get; set; }
        public Nullable<int> NUMERO_VERSION { get; set; }
        public string ACTIVO { get; set; }
        public Nullable<System.DateTime> FECHA_CREA { get; set; }
        public string USUARIO_CREA { get; set; }
    
        public virtual ICollection<MAE_SOLICITUD_INSPECCION> MAE_SOLICITUD_INSPECCION { get; set; }
    }
}
