//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGESDOC.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAE_DESTINO_SOLICITUD_INSPECCION
    {
        public int ID_DEST_SOL_INS { get; set; }
        public string NOMBRE { get; set; }
        public string ACTIVO { get; set; }
    }
}
