//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGESDOC.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAE_DOCUMENTO
    {
        public MAE_DOCUMENTO()
        {
            this.DAT_DOCUMENTO_DETALLE = new HashSet<DAT_DOCUMENTO_DETALLE>();
            this.MAE_DOCUMENTO_ANEXO = new HashSet<MAE_DOCUMENTO_ANEXO>();
        }
    
        public int ID_DOCUMENTO { get; set; }
        public int NUMERO { get; set; }
        public byte ID_TIPO_DOCUMENTO { get; set; }
        public Nullable<int> NUMERO_DOCUMENTO { get; set; }
        public string ANEXOS { get; set; }
        public int FOLIOS { get; set; }
        public int OFICINA_CREA { get; set; }
        public System.DateTime FECHA_ENVIO { get; set; }
        public string USUARIO_CREA { get; set; }
        public string NOM_DOC { get; set; }
        public string PERSONA_CREA { get; set; }
        public Nullable<byte> ID_INDICADOR_DOCUMENTO { get; set; }
        public string RUTA_PDF { get; set; }
        public Nullable<int> NUM_EXT { get; set; }
        public string NOM_OFICINA_CREA { get; set; }
    
        public virtual ICollection<DAT_DOCUMENTO_DETALLE> DAT_DOCUMENTO_DETALLE { get; set; }
        public virtual MAE_DOCUMENTO_INDICADOR MAE_DOCUMENTO_INDICADOR { get; set; }
        public virtual MAE_HOJA_TRAMITE MAE_HOJA_TRAMITE { get; set; }
        public virtual MAE_TIPO_DOCUMENTO MAE_TIPO_DOCUMENTO { get; set; }
        public virtual ICollection<MAE_DOCUMENTO_ANEXO> MAE_DOCUMENTO_ANEXO { get; set; }
    }
}
