//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGESDOC.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAE_SOLICITUD_INSPECCION
    {
        public MAE_SOLICITUD_INSPECCION()
        {
            this.MAE_ACTA_INSPECCION_DSFPA = new HashSet<MAE_ACTA_INSPECCION_DSFPA>();
            this.MAE_INFORME_INSPECCION_DSFPA = new HashSet<MAE_INFORME_INSPECCION_DSFPA>();
            this.MAE_PRUEBA_INSPECCION_DSFPA = new HashSet<MAE_PRUEBA_INSPECCION_DSFPA>();
            this.MAE_CHECK_LIST_INSPECCION_DSFPA = new HashSet<MAE_CHECK_LIST_INSPECCION_DSFPA>();
        }
    
        public int ID_SOL_INS { get; set; }
        public Nullable<int> ID_SEGUIMIENTO { get; set; }
        public Nullable<int> NUMERO_DOCUMENTO { get; set; }
        public Nullable<System.DateTime> FECHA_CREA { get; set; }
        public Nullable<int> OFICINA_CREA { get; set; }
        public string USUARIO_CREA { get; set; }
        public Nullable<int> AÑO_CREA { get; set; }
        public Nullable<int> ID_VERSION_SOLICITUD { get; set; }
        public string RESOLUCION { get; set; }
        public string PERSONA_CONTACTO { get; set; }
        public string TELEFONO_OFICINA { get; set; }
        public string TELEFONO_PLANTA { get; set; }
        public string CORREO { get; set; }
        public string OBSERVACIONES { get; set; }
        public Nullable<int> ID_TIPO_SER_HAB { get; set; }
        public Nullable<int> ID_FILIAL { get; set; }
        public Nullable<int> ID_DEST_SOL_INS { get; set; }
        public string COND_MANUALES { get; set; }
        public string NORMA_APLICA { get; set; }
        public Nullable<int> ID_ESTADO { get; set; }
        public string USUARIO_RECEPCION { get; set; }
        public Nullable<System.DateTime> FECHA_RECEPCION { get; set; }
        public string NOM_OFI_CREA { get; set; }
        public Nullable<int> ID_OFICINA_DESTINO { get; set; }
        public string NOM_OFICINA_DESTINO { get; set; }
        public string INSPECTOR { get; set; }
        public Nullable<System.DateTime> FECHA_INSPECCION { get; set; }
        public Nullable<System.DateTime> FECHA_RECEPCION_INSPECTOR { get; set; }
    
        public virtual MAE_VERSION_SOLICITUD MAE_VERSION_SOLICITUD { get; set; }
        public virtual ICollection<MAE_ACTA_INSPECCION_DSFPA> MAE_ACTA_INSPECCION_DSFPA { get; set; }
        public virtual ICollection<MAE_INFORME_INSPECCION_DSFPA> MAE_INFORME_INSPECCION_DSFPA { get; set; }
        public virtual ICollection<MAE_PRUEBA_INSPECCION_DSFPA> MAE_PRUEBA_INSPECCION_DSFPA { get; set; }
        public virtual ICollection<MAE_CHECK_LIST_INSPECCION_DSFPA> MAE_CHECK_LIST_INSPECCION_DSFPA { get; set; }
        public virtual MAE_SEGUIMIENTO_DHCPA MAE_SEGUIMIENTO_DHCPA { get; set; }
    }
}
