//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGESDOC.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAE_TIPO_DOCUMENTO_SEGUIMIENTO_ADJUNTO
    {
        public MAE_TIPO_DOCUMENTO_SEGUIMIENTO_ADJUNTO()
        {
            this.MAE_DOCUMENTO_SEGUIMIENTO_ADJUNTO = new HashSet<MAE_DOCUMENTO_SEGUIMIENTO_ADJUNTO>();
        }
    
        public int ID_TIPO_DOC_SEG_ADJUNTO { get; set; }
        public string NOMBRE { get; set; }
        public string ACTIVO { get; set; }
        public Nullable<int> ID_TIPO_SEGUIMIENTO { get; set; }
    
        public virtual ICollection<MAE_DOCUMENTO_SEGUIMIENTO_ADJUNTO> MAE_DOCUMENTO_SEGUIMIENTO_ADJUNTO { get; set; }
        public virtual MAE_TIPO_SEGUIMIENTO MAE_TIPO_SEGUIMIENTO { get; set; }
    }
}
