//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGESDOC.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAE_DOCUMENTO_INDICADOR
    {
        public MAE_DOCUMENTO_INDICADOR()
        {
            this.MAE_DOCUMENTO = new HashSet<MAE_DOCUMENTO>();
        }
    
        public byte ID_INDICADOR_DOCUMENTO { get; set; }
        public string NOMBRE { get; set; }
    
        public virtual ICollection<MAE_DOCUMENTO> MAE_DOCUMENTO { get; set; }
    }
}
