//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGESDOC.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAE_FILIAL_DHCPA
    {
        public int ID_FILIAL { get; set; }
        public string NOMBRE { get; set; }
        public string TP_E_I { get; set; }
        public Nullable<int> SOL_INSP { get; set; }
        public Nullable<int> ID_OD_INSP { get; set; }
    }
}
