//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGESDOC.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAE_DOCUMENTO_INDICADOR
    {
        public MAE_DOCUMENTO_INDICADOR()
        {
            this.MAE_DOCUMENTO = new HashSet<MAE_DOCUMENTO>();
        }
    
        public byte ID_INDICADOR_DOCUMENTO { get; set; }
        public string NOMBRE { get; set; }
    
        public virtual ICollection<MAE_DOCUMENTO> MAE_DOCUMENTO { get; set; }
    }
}
