//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGESDOC.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAE_TIPO_LICENCIA_OPERACION
    {
        public MAE_TIPO_LICENCIA_OPERACION()
        {
            this.DAT_PROTOCOLO_LICENCIA_OPERACION = new HashSet<DAT_PROTOCOLO_LICENCIA_OPERACION>();
        }
    
        public int ID_TIPO_LICENCIA_OPERACION { get; set; }
        public string NOMBRE { get; set; }
        public string RUTA_PDF { get; set; }
        public string ACTIVO { get; set; }
    
        public virtual ICollection<DAT_PROTOCOLO_LICENCIA_OPERACION> DAT_PROTOCOLO_LICENCIA_OPERACION { get; set; }
    }
}
