//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGESDOC.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class VISTA_DB_GENERAL_MAE_UNIDAD_MEDIDA
    {
        public int ID_UM { get; set; }
        public string NOMBRE { get; set; }
        public string SIGLAS { get; set; }
        public string ACTIVO { get; set; }
    }
}
