//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGESDOC.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_CONSULTAR_TIPO_DOCUMENTO_IDENTIDAD
    {
        public byte TIPO_DOC_IDEN { get; set; }
        public string NOMBRE { get; set; }
        public string SIGLAS { get; set; }
        public Nullable<int> CANT_CARACTERES { get; set; }
    }
}
