//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGESDOC.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_CONSULTAR_COD_HAB_ALMACEN
    {
        public int ID_CODIGO_ALMACEN { get; set; }
        public string SIGLAS { get; set; }
        public string NOMBRE { get; set; }
        public string ACTIVO { get; set; }
    }
}
