//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGESDOC.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_CONSULTAR_PENDIENTES_HT_PARA_ADJUNTAR_20190104
    {
        public int OFICINA_DESTINO { get; set; }
        public string OFICINA { get; set; }
        public string persona_num_documento { get; set; }
        public string NOMBRE { get; set; }
        public string HOJA_TRAMITE { get; set; }
    }
}
