//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGESDOC.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_CONSULTAR_ACTV_ALMACEN
    {
        public int ID_ACTIVIDAD_ALMACEN { get; set; }
        public string NOMBRE_ACTIVIDAD { get; set; }
        public string RUTA_PDF { get; set; }
        public string ACTIVO { get; set; }
    }
}
