//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGESDOC.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_CONSULTA_DB_GENERAL_MAE_FACTURA
    {
        public int ID_FACTURA { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
        public string FECHA_TEXT { get; set; }
        public string COMPROBANTE { get; set; }
        public string IMPORTE { get; set; }
        public string TUPA_SERV { get; set; }
        public string VALOR_FACT_EXP { get; set; }
        public string DOCUMENTO { get; set; }
        public string EXTERNO { get; set; }
        public string DIRECCION { get; set; }
        public string OPERACIONES { get; set; }
        public string TIPO_FACTURA { get; set; }
        public string USUARIO_REGISTRO { get; set; }
        public string RUTA_PDF { get; set; }
        public Nullable<int> ID_OPERACION { get; set; }
    }
}
