//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGESDOC.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_CONSULTA_EXPEDIENTE_X_EXPEDIENTE
    {
        public string EXPEDIENTE { get; set; }
        public Nullable<int> ID_EXPEDIENTE { get; set; }
        public int ID_SEGUIMIENTO { get; set; }
        public string NUM_DOCUMENTO { get; set; }
        public string EXTERNO { get; set; }
        public string DIRECCION { get; set; }
        public string EVALUADOR { get; set; }
    }
}
