//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGESDOC.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_CONSULTAR_USUARIO
    {
        public string RUC { get; set; }
        public string persona_num_documento { get; set; }
        public int ID_PERFIL { get; set; }
        public string empresa { get; set; }
        public string razon_social { get; set; }
        public string persona { get; set; }
        public string perfil { get; set; }
        public int ID_OFICINA_DIRECCION { get; set; }
        public int ID_OFICINA { get; set; }
        public string NOM_OFI { get; set; }
        public int ID_SEDE { get; set; }
        public string NOM_SEDE { get; set; }
        public Nullable<int> ID_PERFIL_JEFE_OD { get; set; }
        public Nullable<int> ID_PERFIL_INSPECTOR_OD { get; set; }
    }
}
