//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGESDOC.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_CONSULTA_DB_GENERAL_MAE_VALOR_FACTURADO_EXP
    {
        public int ID_VALOR_FAC_EXP { get; set; }
        public string NOMBRE { get; set; }
    }
}
