//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGESDOC.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_CONSULTA_REPORTE_DIARIO_SERIE1
    {
        public string NUM_FACT { get; set; }
        public string FECHA { get; set; }
        public string DOCUMENTO { get; set; }
        public string DATOS { get; set; }
        public string CONCEPTO { get; set; }
        public string EXPEDIENTE { get; set; }
        public int CANTIDAD { get; set; }
        public string TUPA { get; set; }
        public Nullable<decimal> IMPORTE_TOTAL { get; set; }
        public string OPERACION { get; set; }
        public string FECHA_OPERACION { get; set; }
        public int ID_FACTURA { get; set; }
        public Nullable<int> ID_TIPO_FACTURA { get; set; }
        public string FECHA_NUM { get; set; }
        public string N_OFICINA_CREA { get; set; }
    }
}
