//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGESDOC.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_CONSULTA_RECIBO_SERIE1
    {
        public int ID_FACTURA { get; set; }
        public string NOMBRE { get; set; }
        public string DIRECCION { get; set; }
        public string RUC_DNI { get; set; }
        public string FECHA_EMISION { get; set; }
        public string DIA { get; set; }
        public string AÑO { get; set; }
        public string MES_TEXT { get; set; }
        public string LETRA_IMPORTE { get; set; }
        public Nullable<decimal> IMPORTE_TOTAL { get; set; }
        public Nullable<int> DECIMAL_TEXT { get; set; }
        public string NOMBRE_VFE { get; set; }
        public string NUM_FACT { get; set; }
        public string OPERACION { get; set; }
        public string FECHA_OPERACION { get; set; }
        public string TUPA_SERV { get; set; }
        public Nullable<int> CANTIDAD { get; set; }
    }
}
