//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGESDOC.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_CONSULTA_SOLICITUD_INSPECCION_OD
    {
        public int ID_SOL_INS { get; set; }
        public Nullable<int> ID_ESTADO { get; set; }
        public Nullable<System.DateTime> FECHA_CREA { get; set; }
        public string FECHA_CREA_TEXT { get; set; }
        public string EXTERNO { get; set; }
        public string NOMBRE_ESTADO { get; set; }
        public string NOMBRE_TIPO_SOLICITUD { get; set; }
        public string SOLICITUD_INSPECCION { get; set; }
        public Nullable<int> ID_OD_INSP { get; set; }
        public string PERSONA_CONTACTO { get; set; }
        public string TELEFONO_OFICINA { get; set; }
        public string TELEFONO_PLANTA { get; set; }
        public string CORREO { get; set; }
        public string RESOLUCION { get; set; }
        public string OBSERVACIONES { get; set; }
        public string EXPEDIENTE { get; set; }
        public Nullable<int> ID_SEGUIMIENTO { get; set; }
        public string NOMBRE_EXTERNO { get; set; }
        public string INSPECTOR { get; set; }
        public Nullable<System.DateTime> FECHA_INSPECCION { get; set; }
        public Nullable<System.DateTime> FECHA_RECEPCION_INSPECTOR { get; set; }
        public string NOM_INSPECTOR { get; set; }
        public string FECHA_INSPECCION_TEXT { get; set; }
        public string FECHA_RECEPCION_INSPECTOR_TEXT { get; set; }
    }
}
