//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGESDOC.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_CONSULTAR_TIPO_ACTIVIDAD_PLANTA
    {
        public int ID_TIPO_ACTIVIDAD { get; set; }
        public string NOMBRE { get; set; }
        public Nullable<int> ID_TIPO_PLANTA { get; set; }
        public string RUTA_FTP { get; set; }
    }
}
