//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGESDOC.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_CONSULTAR_DB_GENERAL_MAE_CONCESION
    {
        public int ID_CONCESION { get; set; }
        public Nullable<int> ID_AREA_PRODUCCION { get; set; }
        public Nullable<int> ID_TIPO_CONCESION { get; set; }
        public string ACTIVO { get; set; }
        public string RUC { get; set; }
        public string UBIGEO { get; set; }
        public string CODIGO_HABILITACION { get; set; }
        public string RAZON_SOCIAL { get; set; }
        public string DEPARTAMENTO { get; set; }
        public string PROVINCIA { get; set; }
        public string DISTRITO { get; set; }
        public string UBICACION { get; set; }
        public string COD_AREA_PRODUCCION { get; set; }
        public string NOMBRE_AREA_PRODUCCION { get; set; }
        public Nullable<int> ID_ZONA_PRODUCCION { get; set; }
        public string COD_ZONA_PRODUCCION { get; set; }
        public string NOMBRE_ZONA_PRODUCCION { get; set; }
        public string PARTIDA_REGISTRAL { get; set; }
        public string TIPO_CONCESION { get; set; }
        public Nullable<int> ID_TIP_ACT_CONCE { get; set; }
        public string ACTIVIDAD_CONCESION { get; set; }
    }
}
