//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGESDOC.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_CONSULTAR_DNI_PERSONAL_LEGAL
    {
        public int ID_DNI_PERSONA_LEGAL { get; set; }
        public string DNI { get; set; }
        public string DOCUMENTO { get; set; }
        public string NOMBRES_Y_APELLIDOS { get; set; }
        public string TELEFONO { get; set; }
        public string CORREO { get; set; }
        public string FECHA_REGISTRO { get; set; }
        public string FECHA_DESACTIVADO { get; set; }
        public Nullable<int> ACTIVO { get; set; }
    }
}
