//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGESDOC.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_CONSULTAR_PERSONA_TELEFONO
    {
        public int ID_PERSONA_TELEFONO { get; set; }
        public string PERSONA_NUM_DOCUMENTO { get; set; }
        public string TELEFONO1 { get; set; }
        public string ACTIVO { get; set; }
    }
}
