//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGESDOC.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_CONSULTA_PENDIENTES_SANIPES_DETALLE
    {
        public string HOJA_TRAMITE { get; set; }
        public System.DateTime FECHA_EMISION { get; set; }
        public Nullable<int> TUPA { get; set; }
        public string ASUNTO_TUPA { get; set; }
        public string ESTADO { get; set; }
        public System.DateTime FECHA_ENVIO { get; set; }
        public Nullable<System.DateTime> FECHA_RECEPCION { get; set; }
        public string OFICINA { get; set; }
        public string ASUNTO { get; set; }
        public string DESTINO { get; set; }
        public string PERSONA_ENVIA { get; set; }
    }
}
