//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGESDOC.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_CONSULTAR_PERSONAL
    {
        public int ID_PER_EMPRESA { get; set; }
        public string persona_num_documento { get; set; }
        public string NOM_PERSONA { get; set; }
        public bool ACTIVO { get; set; }
        public int ID_OFICINA_DIRECCION { get; set; }
        public int ID_OFICINA { get; set; }
        public string NOM_OFI { get; set; }
        public int ID_SEDE { get; set; }
        public string NOM_SEDE { get; set; }
        public string RUC { get; set; }
        public string RAZON_SOCIAL { get; set; }
    }
}
