//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGESDOC.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_CONSULTAR_SEDE_OFICINA
    {
        public int ID_SEDE { get; set; }
        public string NOMBRE { get; set; }
        public string DIRECCION { get; set; }
        public string REFERENCIA { get; set; }
        public string UBIGEO { get; set; }
        public bool ACTIVO { get; set; }
        public int ID_OFICINA { get; set; }
    }
}
