//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGESDOC.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_CONSULTAR_DIRECCION
    {
        public int ID_OFICINA_DIRECCION { get; set; }
        public int ID_OFICINA { get; set; }
        public int ID_SEDE { get; set; }
        public bool ACTIVO { get; set; }
    }
}
