//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGESDOC.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_CONSULTA_DB_GENERAL_MAE_FACTURA
    {
        public int ID_FACTURA { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
        public string FECHA_TEXT { get; set; }
        public string COMPROBANTE { get; set; }
        public string IMPORTE { get; set; }
        public string TUPA_SERV { get; set; }
        public string VALOR_FACT_EXP { get; set; }
        public string DOCUMENTO { get; set; }
        public string EXTERNO { get; set; }
        public string DIRECCION { get; set; }
        public string OPERACIONES { get; set; }
        public string TIPO_FACTURA { get; set; }
        public string USUARIO_REGISTRO { get; set; }
        public string RUTA_PDF { get; set; }
        public Nullable<int> ID_OPERACION { get; set; }
    }
}
