//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGESDOC.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_CONSULTAR_PERSONAL
    {
        public int ID_PER_EMPRESA { get; set; }
        public string persona_num_documento { get; set; }
        public string NOM_PERSONA { get; set; }
        public bool ACTIVO { get; set; }
        public int ID_OFICINA_DIRECCION { get; set; }
        public int ID_OFICINA { get; set; }
        public string NOM_OFI { get; set; }
        public int ID_SEDE { get; set; }
        public string NOM_SEDE { get; set; }
        public string RUC { get; set; }
        public string RAZON_SOCIAL { get; set; }
    }
}
