//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGESDOC.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_CONSULTAR_DB_GENERAL_MAE_ALMACEN_SEDE
    {
        public int ID_ALMACEN { get; set; }
        public Nullable<int> ID_SEDE { get; set; }
        public Nullable<int> ID_CODIGO_ALMACEN { get; set; }
        public Nullable<int> NUM_ALMACEN { get; set; }
        public string NOM_ALMACEN { get; set; }
        public string CODIGO_HABILITANTE { get; set; }
        public Nullable<int> ID_FILIAL { get; set; }
        public Nullable<int> ID_ACTIVIDAD_ALMACEN { get; set; }
        public Nullable<System.DateTime> FECHA_REGISTRO { get; set; }
        public string USUARIO_REGISTRO { get; set; }
        public Nullable<System.DateTime> FECHA_MODIFICA { get; set; }
        public string USUARIO_MODIFICA { get; set; }
        public Nullable<System.DateTime> FECHA_DESACTIVADO { get; set; }
        public string USUARIO_DESACTIVADO { get; set; }
        public string ACTIVO { get; set; }
    }
}
