//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGESDOC.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_CONSULTAR_PENDIENTES_HT_PARA_ADJUNTAR_20190104
    {
        public int OFICINA_DESTINO { get; set; }
        public string OFICINA { get; set; }
        public string persona_num_documento { get; set; }
        public string NOMBRE { get; set; }
        public string HOJA_TRAMITE { get; set; }
    }
}
