//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGESDOC.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_CONSULTAR_DB_GENERAL_MAE_AREA_PRODUCCION
    {
        public int ID_AREA_PRODUCCION { get; set; }
        public Nullable<int> ID_ZONA_PRODUCCION { get; set; }
        public Nullable<int> ID_ESTADO_AREA_PRO { get; set; }
        public Nullable<int> ID_TIPO_AREA_PRO { get; set; }
        public string ESTADO { get; set; }
        public string COD_ZONA_PRODUCCION { get; set; }
        public string UNION_EUROPEA { get; set; }
        public string COD_UNION_EUROPEA { get; set; }
        public string COD_AREA_PRODUCCION { get; set; }
        public string NOMBRE { get; set; }
        public string TIPO_AREA { get; set; }
    }
}
