//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGESDOC.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_CONSULTAR_OFICINA_DIRECCION_LEGAL
    {
        public Nullable<int> ID_OFICINA_DIRECCION_LEGAL { get; set; }
        public int ID_SEDE { get; set; }
        public string RUC { get; set; }
        public string DIRECCION { get; set; }
        public string UBIGEO { get; set; }
        public string FECHA_REGISTRO { get; set; }
        public string FECHA_DESACTIVADO { get; set; }
        public Nullable<int> ACTIVO { get; set; }
        public string ID_UBIGEO { get; set; }
        public string NOM_SEDE { get; set; }
        public string NOM_DIRECCION { get; set; }
        public string NOM_REFERENCIA { get; set; }
    }
}
