//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGESDOC.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_CONSULTAR_PERSONA_TELEFONO
    {
        public int ID_PERSONA_TELEFONO { get; set; }
        public string PERSONA_NUM_DOCUMENTO { get; set; }
        public string TELEFONO1 { get; set; }
        public string ACTIVO { get; set; }
    }
}
