//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGESDOC.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_CONSULTA_FACTURAS
    {
        public int ID_FACTURA { get; set; }
        public Nullable<int> NUM1_FACT { get; set; }
        public Nullable<int> NUM2_FACT { get; set; }
        public Nullable<System.DateTime> FECHA_FACT { get; set; }
        public Nullable<decimal> IMPORTE_TOTAL { get; set; }
        public Nullable<System.DateTime> FECHA_REGISTRO { get; set; }
        public string USUARIO_REGISTRO { get; set; }
        public string ACTIVO { get; set; }
        public Nullable<int> ID_TIPO_FACTURA { get; set; }
        public string TIPO_FACTURA { get; set; }
    }
}
