//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGESDOC.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_CONSULTA_REPORTE_DIARIO_SERIE1
    {
        public string NUM_FACT { get; set; }
        public string FECHA { get; set; }
        public string DOCUMENTO { get; set; }
        public string DATOS { get; set; }
        public string CONCEPTO { get; set; }
        public string EXPEDIENTE { get; set; }
        public int CANTIDAD { get; set; }
        public string TUPA { get; set; }
        public Nullable<decimal> IMPORTE_TOTAL { get; set; }
        public string OPERACION { get; set; }
        public string FECHA_OPERACION { get; set; }
        public int ID_FACTURA { get; set; }
        public Nullable<int> ID_TIPO_FACTURA { get; set; }
        public string FECHA_NUM { get; set; }
        public string N_OFICINA_CREA { get; set; }
    }
}
