//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGESDOC.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_CONSULTAR_DB_GENERAL_MAE_ALMACEN_SEDE
    {
        public int ID_ALMACEN { get; set; }
        public Nullable<int> ID_SEDE { get; set; }
        public Nullable<int> ID_CODIGO_ALMACEN { get; set; }
        public Nullable<int> NUM_ALMACEN { get; set; }
        public string NOM_ALMACEN { get; set; }
        public string CODIGO_HABILITANTE { get; set; }
        public Nullable<int> ID_FILIAL { get; set; }
        public Nullable<int> ID_ACTIVIDAD_ALMACEN { get; set; }
        public Nullable<System.DateTime> FECHA_REGISTRO { get; set; }
        public string USUARIO_REGISTRO { get; set; }
        public Nullable<System.DateTime> FECHA_MODIFICA { get; set; }
        public string USUARIO_MODIFICA { get; set; }
        public Nullable<System.DateTime> FECHA_DESACTIVADO { get; set; }
        public string USUARIO_DESACTIVADO { get; set; }
        public string ACTIVO { get; set; }
    }
}
