//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGESDOC.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_CONSULTAR_PROVINCIA
    {
        public int ID_PROVINCIA { get; set; }
        public string CODIGO_DEPARTAMENTO { get; set; }
        public string CODIGO_PROVINCIA { get; set; }
        public string PROVINCIA { get; set; }
    }
}
