//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGESDOC.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_DB_GENERAL_MAE_DESEMBARCADERO
    {
        public int ID_DESEMBARCADERO { get; set; }
        public Nullable<int> ID_SEDE { get; set; }
        public Nullable<int> ID_TIPO_DESEMBARCADERO { get; set; }
        public string ENTIDAD { get; set; }
        public string NOMBRE_TIPO_DESEMBARCADERO { get; set; }
        public string DENOMINACION { get; set; }
        public Nullable<double> LATITUD { get; set; }
        public Nullable<double> LONGITUD { get; set; }
        public string CODIGO_DESEMBARCADERO { get; set; }
        public string ESTADO_DESEMB { get; set; }
    }
}
