//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGESDOC.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_DB_GENERAL_MAE_CODIGO_DESEMBARCADERO
    {
        public int ID_COD_DESEMB { get; set; }
        public string CODIGO { get; set; }
        public Nullable<int> ID_TIPO_DESEMBARCADERO { get; set; }
        public string ACTIVO { get; set; }
    }
}
