//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGESDOC.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_VER_PEDIENTES_GESDOC
    {
        public Nullable<int> ANIO { get; set; }
        public int ID_OFICINA { get; set; }
        public Nullable<int> TUPA { get; set; }
        public Nullable<int> CANT { get; set; }
    }
}
