//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 414
namespace SIGESDOC.VSTO_SANIPES {
    
    
    /// 
    [Microsoft.VisualStudio.Tools.Applications.Runtime.StartupObjectAttribute(0)]
    [global::System.Security.Permissions.PermissionSetAttribute(global::System.Security.Permissions.SecurityAction.Demand, Name="FullTrust")]
    public sealed partial class ThisDocument : Microsoft.Office.Tools.Word.DocumentBase {
        
        internal Microsoft.Office.Tools.ActionsPane ActionsPane;
        
        internal Microsoft.Office.Tools.Word.Bookmark NON_DOC;
        
        internal Microsoft.Office.Tools.Word.Bookmark EXP_O_HT_N_CDL_NOTIF;
        
        internal Microsoft.Office.Tools.Word.Bookmark EMPRESA_CDL_NOTIF;
        
        internal Microsoft.Office.Tools.Word.Bookmark ASUNTO;
        
        internal Microsoft.Office.Tools.Word.Bookmark DIRECCION_CDL_NOTIF;
        
        internal Microsoft.Office.Tools.Word.Bookmark FOLIA_CDL_NOTIF;
        
        internal Microsoft.Office.Tools.Word.Bookmark DOC_NOTIFICAR_CDL_NOTIF;
        
        internal Microsoft.Office.Tools.Word.Bookmark A_NON_DOC1;
        
        internal Microsoft.Office.Tools.Word.Bookmark A_DIRECCION_CDL_NOTIF1;
        
        internal Microsoft.Office.Tools.Word.Bookmark A_DOC_NOTIFICAR_CDL_NOTIF1;
        
        internal Microsoft.Office.Tools.Word.Bookmark A_EXP_O_HT_N_CDL_NOTIF1;
        
        internal Microsoft.Office.Tools.Word.Bookmark A_NON_DOC2;
        
        internal Microsoft.Office.Tools.Word.Bookmark A_DIRECCION_CDL_NOTIF2;
        
        internal Microsoft.Office.Tools.Word.Bookmark A_DOC_NOTIFICAR_CDL_NOTIF2;
        
        internal Microsoft.Office.Tools.Word.Bookmark A_EXP_O_HT_N_CDL_NOTIF2;
        
        internal Microsoft.Office.Tools.Word.Bookmark A_NON_DOC3;
        
        internal Microsoft.Office.Tools.Word.Bookmark A_DIRECCION_CDL_NOTIF3;
        
        internal Microsoft.Office.Tools.Word.Bookmark A_DOC_NOTIFICAR_CDL_NOTIF3;
        
        internal Microsoft.Office.Tools.Word.Bookmark A_EXP_O_HT_N_CDL_NOTIF3;
        
        internal Microsoft.Office.Tools.Word.Bookmark A_NON_DOC4;
        
        internal Microsoft.Office.Tools.Word.Bookmark A_DIRECCION_CDL_NOTIF4;
        
        internal Microsoft.Office.Tools.Word.Bookmark A_DOC_NOTIFICAR_CDL_NOTIF4;
        
        internal Microsoft.Office.Tools.Word.Bookmark A_EXP_O_HT_N_CDL_NOTIF4;
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "15.0.0.0")]
        private global::System.Object missing = global::System.Type.Missing;
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "15.0.0.0")]
        internal Microsoft.Office.Interop.Word.Application ThisApplication;
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        public ThisDocument(global::Microsoft.Office.Tools.Word.Factory factory, global::System.IServiceProvider serviceProvider) : 
                base(factory, serviceProvider, "ThisDocument", "ThisDocument") {
            Globals.Factory = factory;
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "15.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected override void Initialize() {
            base.Initialize();
            this.ThisApplication = this.GetHostItem<Microsoft.Office.Interop.Word.Application>(typeof(Microsoft.Office.Interop.Word.Application), "Application");
            Globals.ThisDocument = this;
            global::System.Windows.Forms.Application.EnableVisualStyles();
            this.InitializeCachedData();
            this.InitializeControls();
            this.InitializeComponents();
            this.InitializeData();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "15.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected override void FinishInitialization() {
            this.InternalStartup();
            this.OnStartup();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "15.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected override void InitializeDataBindings() {
            this.BeginInitialization();
            this.BindToData();
            this.EndInitialization();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "15.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void InitializeCachedData() {
            if ((this.DataHost == null)) {
                return;
            }
            if (this.DataHost.IsCacheInitialized) {
                this.DataHost.FillCachedData(this);
            }
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "15.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void InitializeData() {
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "15.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void BindToData() {
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        private void StartCaching(string MemberName) {
            this.DataHost.StartCaching(this, MemberName);
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        private void StopCaching(string MemberName) {
            this.DataHost.StopCaching(this, MemberName);
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        private bool IsCached(string MemberName) {
            return this.DataHost.IsCached(this, MemberName);
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "15.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void BeginInitialization() {
            this.BeginInit();
            this.ActionsPane.BeginInit();
            this.NON_DOC.BeginInit();
            this.EXP_O_HT_N_CDL_NOTIF.BeginInit();
            this.EMPRESA_CDL_NOTIF.BeginInit();
            this.ASUNTO.BeginInit();
            this.DIRECCION_CDL_NOTIF.BeginInit();
            this.FOLIA_CDL_NOTIF.BeginInit();
            this.DOC_NOTIFICAR_CDL_NOTIF.BeginInit();
            this.A_NON_DOC1.BeginInit();
            this.A_DIRECCION_CDL_NOTIF1.BeginInit();
            this.A_DOC_NOTIFICAR_CDL_NOTIF1.BeginInit();
            this.A_EXP_O_HT_N_CDL_NOTIF1.BeginInit();
            this.A_NON_DOC2.BeginInit();
            this.A_DIRECCION_CDL_NOTIF2.BeginInit();
            this.A_DOC_NOTIFICAR_CDL_NOTIF2.BeginInit();
            this.A_EXP_O_HT_N_CDL_NOTIF2.BeginInit();
            this.A_NON_DOC3.BeginInit();
            this.A_DIRECCION_CDL_NOTIF3.BeginInit();
            this.A_DOC_NOTIFICAR_CDL_NOTIF3.BeginInit();
            this.A_EXP_O_HT_N_CDL_NOTIF3.BeginInit();
            this.A_NON_DOC4.BeginInit();
            this.A_DIRECCION_CDL_NOTIF4.BeginInit();
            this.A_DOC_NOTIFICAR_CDL_NOTIF4.BeginInit();
            this.A_EXP_O_HT_N_CDL_NOTIF4.BeginInit();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "15.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void EndInitialization() {
            this.A_EXP_O_HT_N_CDL_NOTIF4.EndInit();
            this.A_DOC_NOTIFICAR_CDL_NOTIF4.EndInit();
            this.A_DIRECCION_CDL_NOTIF4.EndInit();
            this.A_NON_DOC4.EndInit();
            this.A_EXP_O_HT_N_CDL_NOTIF3.EndInit();
            this.A_DOC_NOTIFICAR_CDL_NOTIF3.EndInit();
            this.A_DIRECCION_CDL_NOTIF3.EndInit();
            this.A_NON_DOC3.EndInit();
            this.A_EXP_O_HT_N_CDL_NOTIF2.EndInit();
            this.A_DOC_NOTIFICAR_CDL_NOTIF2.EndInit();
            this.A_DIRECCION_CDL_NOTIF2.EndInit();
            this.A_NON_DOC2.EndInit();
            this.A_EXP_O_HT_N_CDL_NOTIF1.EndInit();
            this.A_DOC_NOTIFICAR_CDL_NOTIF1.EndInit();
            this.A_DIRECCION_CDL_NOTIF1.EndInit();
            this.A_NON_DOC1.EndInit();
            this.DOC_NOTIFICAR_CDL_NOTIF.EndInit();
            this.FOLIA_CDL_NOTIF.EndInit();
            this.DIRECCION_CDL_NOTIF.EndInit();
            this.ASUNTO.EndInit();
            this.EMPRESA_CDL_NOTIF.EndInit();
            this.EXP_O_HT_N_CDL_NOTIF.EndInit();
            this.NON_DOC.EndInit();
            this.ActionsPane.EndInit();
            this.EndInit();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "15.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void InitializeControls() {
            this.ActionsPane = Globals.Factory.CreateActionsPane(null, null, "ActionsPane", "ActionsPane", this);
            this.NON_DOC = Globals.Factory.CreateBookmark(null, null, "NON_DOC", "NON_DOC", this);
            this.EXP_O_HT_N_CDL_NOTIF = Globals.Factory.CreateBookmark(null, null, "EXP_O_HT_N_CDL_NOTIF", "EXP_O_HT_N_CDL_NOTIF", this);
            this.EMPRESA_CDL_NOTIF = Globals.Factory.CreateBookmark(null, null, "EMPRESA_CDL_NOTIF", "EMPRESA_CDL_NOTIF", this);
            this.ASUNTO = Globals.Factory.CreateBookmark(null, null, "ASUNTO", "ASUNTO", this);
            this.DIRECCION_CDL_NOTIF = Globals.Factory.CreateBookmark(null, null, "DIRECCION_CDL_NOTIF", "DIRECCION_CDL_NOTIF", this);
            this.FOLIA_CDL_NOTIF = Globals.Factory.CreateBookmark(null, null, "FOLIA_CDL_NOTIF", "FOLIA_CDL_NOTIF", this);
            this.DOC_NOTIFICAR_CDL_NOTIF = Globals.Factory.CreateBookmark(null, null, "DOC_NOTIFICAR_CDL_NOTIF", "DOC_NOTIFICAR_CDL_NOTIF", this);
            this.A_NON_DOC1 = Globals.Factory.CreateBookmark(null, null, "A_NON_DOC1", "A_NON_DOC1", this);
            this.A_DIRECCION_CDL_NOTIF1 = Globals.Factory.CreateBookmark(null, null, "A_DIRECCION_CDL_NOTIF1", "A_DIRECCION_CDL_NOTIF1", this);
            this.A_DOC_NOTIFICAR_CDL_NOTIF1 = Globals.Factory.CreateBookmark(null, null, "A_DOC_NOTIFICAR_CDL_NOTIF1", "A_DOC_NOTIFICAR_CDL_NOTIF1", this);
            this.A_EXP_O_HT_N_CDL_NOTIF1 = Globals.Factory.CreateBookmark(null, null, "A_EXP_O_HT_N_CDL_NOTIF1", "A_EXP_O_HT_N_CDL_NOTIF1", this);
            this.A_NON_DOC2 = Globals.Factory.CreateBookmark(null, null, "A_NON_DOC2", "A_NON_DOC2", this);
            this.A_DIRECCION_CDL_NOTIF2 = Globals.Factory.CreateBookmark(null, null, "A_DIRECCION_CDL_NOTIF2", "A_DIRECCION_CDL_NOTIF2", this);
            this.A_DOC_NOTIFICAR_CDL_NOTIF2 = Globals.Factory.CreateBookmark(null, null, "A_DOC_NOTIFICAR_CDL_NOTIF2", "A_DOC_NOTIFICAR_CDL_NOTIF2", this);
            this.A_EXP_O_HT_N_CDL_NOTIF2 = Globals.Factory.CreateBookmark(null, null, "A_EXP_O_HT_N_CDL_NOTIF2", "A_EXP_O_HT_N_CDL_NOTIF2", this);
            this.A_NON_DOC3 = Globals.Factory.CreateBookmark(null, null, "A_NON_DOC3", "A_NON_DOC3", this);
            this.A_DIRECCION_CDL_NOTIF3 = Globals.Factory.CreateBookmark(null, null, "A_DIRECCION_CDL_NOTIF3", "A_DIRECCION_CDL_NOTIF3", this);
            this.A_DOC_NOTIFICAR_CDL_NOTIF3 = Globals.Factory.CreateBookmark(null, null, "A_DOC_NOTIFICAR_CDL_NOTIF3", "A_DOC_NOTIFICAR_CDL_NOTIF3", this);
            this.A_EXP_O_HT_N_CDL_NOTIF3 = Globals.Factory.CreateBookmark(null, null, "A_EXP_O_HT_N_CDL_NOTIF3", "A_EXP_O_HT_N_CDL_NOTIF3", this);
            this.A_NON_DOC4 = Globals.Factory.CreateBookmark(null, null, "A_NON_DOC4", "A_NON_DOC4", this);
            this.A_DIRECCION_CDL_NOTIF4 = Globals.Factory.CreateBookmark(null, null, "A_DIRECCION_CDL_NOTIF4", "A_DIRECCION_CDL_NOTIF4", this);
            this.A_DOC_NOTIFICAR_CDL_NOTIF4 = Globals.Factory.CreateBookmark(null, null, "A_DOC_NOTIFICAR_CDL_NOTIF4", "A_DOC_NOTIFICAR_CDL_NOTIF4", this);
            this.A_EXP_O_HT_N_CDL_NOTIF4 = Globals.Factory.CreateBookmark(null, null, "A_EXP_O_HT_N_CDL_NOTIF4", "A_EXP_O_HT_N_CDL_NOTIF4", this);
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "15.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void InitializeComponents() {
            // 
            // ActionsPane
            // 
            this.ActionsPane.AutoSize = false;
            this.ActionsPane.AutoValidate = System.Windows.Forms.AutoValidate.EnablePreventFocusChange;
            // 
            // NON_DOC
            // 
            this.NON_DOC.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // EXP_O_HT_N_CDL_NOTIF
            // 
            this.EXP_O_HT_N_CDL_NOTIF.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // EMPRESA_CDL_NOTIF
            // 
            this.EMPRESA_CDL_NOTIF.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // ASUNTO
            // 
            this.ASUNTO.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // DIRECCION_CDL_NOTIF
            // 
            this.DIRECCION_CDL_NOTIF.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // FOLIA_CDL_NOTIF
            // 
            this.FOLIA_CDL_NOTIF.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // DOC_NOTIFICAR_CDL_NOTIF
            // 
            this.DOC_NOTIFICAR_CDL_NOTIF.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // A_NON_DOC1
            // 
            this.A_NON_DOC1.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // A_DIRECCION_CDL_NOTIF1
            // 
            this.A_DIRECCION_CDL_NOTIF1.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // A_DOC_NOTIFICAR_CDL_NOTIF1
            // 
            this.A_DOC_NOTIFICAR_CDL_NOTIF1.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // A_EXP_O_HT_N_CDL_NOTIF1
            // 
            this.A_EXP_O_HT_N_CDL_NOTIF1.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // A_NON_DOC2
            // 
            this.A_NON_DOC2.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // A_DIRECCION_CDL_NOTIF2
            // 
            this.A_DIRECCION_CDL_NOTIF2.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // A_DOC_NOTIFICAR_CDL_NOTIF2
            // 
            this.A_DOC_NOTIFICAR_CDL_NOTIF2.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // A_EXP_O_HT_N_CDL_NOTIF2
            // 
            this.A_EXP_O_HT_N_CDL_NOTIF2.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // A_NON_DOC3
            // 
            this.A_NON_DOC3.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // A_DIRECCION_CDL_NOTIF3
            // 
            this.A_DIRECCION_CDL_NOTIF3.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // A_DOC_NOTIFICAR_CDL_NOTIF3
            // 
            this.A_DOC_NOTIFICAR_CDL_NOTIF3.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // A_EXP_O_HT_N_CDL_NOTIF3
            // 
            this.A_EXP_O_HT_N_CDL_NOTIF3.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // A_NON_DOC4
            // 
            this.A_NON_DOC4.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // A_DIRECCION_CDL_NOTIF4
            // 
            this.A_DIRECCION_CDL_NOTIF4.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // A_DOC_NOTIFICAR_CDL_NOTIF4
            // 
            this.A_DOC_NOTIFICAR_CDL_NOTIF4.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // A_EXP_O_HT_N_CDL_NOTIF4
            // 
            this.A_EXP_O_HT_N_CDL_NOTIF4.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // ThisDocument
            // 
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        private bool NeedsFill(string MemberName) {
            return this.DataHost.NeedsFill(this, MemberName);
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "15.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected override void OnShutdown() {
            this.A_EXP_O_HT_N_CDL_NOTIF4.Dispose();
            this.A_DOC_NOTIFICAR_CDL_NOTIF4.Dispose();
            this.A_DIRECCION_CDL_NOTIF4.Dispose();
            this.A_NON_DOC4.Dispose();
            this.A_EXP_O_HT_N_CDL_NOTIF3.Dispose();
            this.A_DOC_NOTIFICAR_CDL_NOTIF3.Dispose();
            this.A_DIRECCION_CDL_NOTIF3.Dispose();
            this.A_NON_DOC3.Dispose();
            this.A_EXP_O_HT_N_CDL_NOTIF2.Dispose();
            this.A_DOC_NOTIFICAR_CDL_NOTIF2.Dispose();
            this.A_DIRECCION_CDL_NOTIF2.Dispose();
            this.A_NON_DOC2.Dispose();
            this.A_EXP_O_HT_N_CDL_NOTIF1.Dispose();
            this.A_DOC_NOTIFICAR_CDL_NOTIF1.Dispose();
            this.A_DIRECCION_CDL_NOTIF1.Dispose();
            this.A_NON_DOC1.Dispose();
            this.DOC_NOTIFICAR_CDL_NOTIF.Dispose();
            this.FOLIA_CDL_NOTIF.Dispose();
            this.DIRECCION_CDL_NOTIF.Dispose();
            this.ASUNTO.Dispose();
            this.EMPRESA_CDL_NOTIF.Dispose();
            this.EXP_O_HT_N_CDL_NOTIF.Dispose();
            this.NON_DOC.Dispose();
            this.ActionsPane.Dispose();
            base.OnShutdown();
        }
    }
    
    /// 
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "15.0.0.0")]
    internal sealed partial class Globals {
        
        /// 
        private Globals() {
        }
        
        private static ThisDocument _ThisDocument;
        
        private static global::Microsoft.Office.Tools.Word.Factory _factory;
        
        private static ThisRibbonCollection _ThisRibbonCollection;
        
        internal static ThisDocument ThisDocument {
            get {
                return _ThisDocument;
            }
            set {
                if ((_ThisDocument == null)) {
                    _ThisDocument = value;
                }
                else {
                    throw new System.NotSupportedException();
                }
            }
        }
        
        internal static global::Microsoft.Office.Tools.Word.Factory Factory {
            get {
                return _factory;
            }
            set {
                if ((_factory == null)) {
                    _factory = value;
                }
                else {
                    throw new System.NotSupportedException();
                }
            }
        }
        
        internal static ThisRibbonCollection Ribbons {
            get {
                if ((_ThisRibbonCollection == null)) {
                    _ThisRibbonCollection = new ThisRibbonCollection(_factory.GetRibbonFactory());
                }
                return _ThisRibbonCollection;
            }
        }
    }
    
    /// 
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "15.0.0.0")]
    internal sealed partial class ThisRibbonCollection : Microsoft.Office.Tools.Ribbon.RibbonCollectionBase {
        
        /// 
        internal ThisRibbonCollection(global::Microsoft.Office.Tools.Ribbon.RibbonFactory factory) : 
                base(factory) {
        }
    }
}
