//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGESDOC.IRepositorio
{
    using SIGESDOC.Entidades;
    using System;
    using System.Collections.Generic;
    
    public partial interface IConsultarPendientesHtParaAdjuntar20190104Repositorio : IBaseRepositorio<VW_CONSULTAR_PENDIENTES_HT_PARA_ADJUNTAR_20190104>
    {
    }
}
