//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGESDOC.IRepositorio
{
    using SIGESDOC.Entidades;
    using System;
    using System.Collections.Generic;
    
    public partial interface ITupaRepositorio : IBaseRepositorio<MAE_TUPA>
    {
    }
}
