//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGESDOC.Repositorio
{
    using SIGESDOC.Entidades;
    using SIGESDOC.IRepositorio;
    using System;
    using System.Collections.Generic;
    
    public partial class ConsultaDbGeneralMaeValorFacturadoExpRepositorio : BaseRepositorio<VW_CONSULTA_DB_GENERAL_MAE_VALOR_FACTURADO_EXP>, IConsultaDbGeneralMaeValorFacturadoExpRepositorio
    {
    	public ConsultaDbGeneralMaeValorFacturadoExpRepositorio(IContext context) : base(context) { }
    }
}
