//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGESDOC.Repositorio
{
    using SIGESDOC.Entidades;
    using SIGESDOC.IRepositorio;
    using System;
    using System.Collections.Generic;
    
    public partial class ConsultarPendientesHtParaAdjuntar20190104Repositorio : BaseRepositorio<VW_CONSULTAR_PENDIENTES_HT_PARA_ADJUNTAR_20190104>, IConsultarPendientesHtParaAdjuntar20190104Repositorio
    {
    	public ConsultarPendientesHtParaAdjuntar20190104Repositorio(IContext context) : base(context) { }
    }
}
