//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGESDOC.Repositorio
{
    using SIGESDOC.Entidades;
    using SIGESDOC.IRepositorio;
    using System;
    using System.Collections.Generic;
    
    public partial class ConsultarActvAlmacenRepositorio : BaseRepositorio<vw_CONSULTAR_ACTV_ALMACEN>, IConsultarActvAlmacenRepositorio
    {
    	public ConsultarActvAlmacenRepositorio(IContext context) : base(context) { }
    }
}
