//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGESDOC.Repositorio
{
    using SIGESDOC.Entidades;
    using SIGESDOC.IRepositorio;
    using System;
    using System.Collections.Generic;
    
    public partial class PtocoloTransporteXIdTransporte2018V1Repositorio : BaseRepositorio<Consultar_ptocolo_transporte_x_id_transporte_2018_v1>, IPtocoloTransporteXIdTransporte2018V1Repositorio
    {
    	public PtocoloTransporteXIdTransporte2018V1Repositorio(IContext context) : base(context) { }
    }
}
