//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGESDOC.Repositorio
{
    using SIGESDOC.Entidades;
    using SIGESDOC.IRepositorio;
    using System;
    using System.Collections.Generic;
    
    public partial class PtocoloTransporteXIdTransporte2018V1Repositorio : BaseRepositorio<Consultar_ptocolo_transporte_x_id_transporte_2018_v1>, IPtocoloTransporteXIdTransporte2018V1Repositorio
    {
    	public PtocoloTransporteXIdTransporte2018V1Repositorio(IContext context) : base(context) { }
    }
}
