//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGESDOC.Host.MesaVirtualService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RecepcionResponse", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class RecepcionResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] bcarstdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ccoduniorgstdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cflgenvcarField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cflgestField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cflgestobsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ctipdocideremField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> dfecmodField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime dfecregField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> dfecregstdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short sidrecextField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string vanioregstdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string vcuoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string vcuorefField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string vdesanxstdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string vnumdocideremField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string vnumregstdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string vobsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string vrucentremField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string vuniorgremField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string vuniorgstdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string vusumodField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string vusuregstdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] bcarstd {
            get {
                return this.bcarstdField;
            }
            set {
                if ((object.ReferenceEquals(this.bcarstdField, value) != true)) {
                    this.bcarstdField = value;
                    this.RaisePropertyChanged("bcarstd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ccoduniorgstd {
            get {
                return this.ccoduniorgstdField;
            }
            set {
                if ((object.ReferenceEquals(this.ccoduniorgstdField, value) != true)) {
                    this.ccoduniorgstdField = value;
                    this.RaisePropertyChanged("ccoduniorgstd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cflgenvcar {
            get {
                return this.cflgenvcarField;
            }
            set {
                if ((object.ReferenceEquals(this.cflgenvcarField, value) != true)) {
                    this.cflgenvcarField = value;
                    this.RaisePropertyChanged("cflgenvcar");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cflgest {
            get {
                return this.cflgestField;
            }
            set {
                if ((object.ReferenceEquals(this.cflgestField, value) != true)) {
                    this.cflgestField = value;
                    this.RaisePropertyChanged("cflgest");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cflgestobs {
            get {
                return this.cflgestobsField;
            }
            set {
                if ((object.ReferenceEquals(this.cflgestobsField, value) != true)) {
                    this.cflgestobsField = value;
                    this.RaisePropertyChanged("cflgestobs");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ctipdociderem {
            get {
                return this.ctipdocideremField;
            }
            set {
                if ((object.ReferenceEquals(this.ctipdocideremField, value) != true)) {
                    this.ctipdocideremField = value;
                    this.RaisePropertyChanged("ctipdociderem");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> dfecmod {
            get {
                return this.dfecmodField;
            }
            set {
                if ((this.dfecmodField.Equals(value) != true)) {
                    this.dfecmodField = value;
                    this.RaisePropertyChanged("dfecmod");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime dfecreg {
            get {
                return this.dfecregField;
            }
            set {
                if ((this.dfecregField.Equals(value) != true)) {
                    this.dfecregField = value;
                    this.RaisePropertyChanged("dfecreg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> dfecregstd {
            get {
                return this.dfecregstdField;
            }
            set {
                if ((this.dfecregstdField.Equals(value) != true)) {
                    this.dfecregstdField = value;
                    this.RaisePropertyChanged("dfecregstd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short sidrecext {
            get {
                return this.sidrecextField;
            }
            set {
                if ((this.sidrecextField.Equals(value) != true)) {
                    this.sidrecextField = value;
                    this.RaisePropertyChanged("sidrecext");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string vanioregstd {
            get {
                return this.vanioregstdField;
            }
            set {
                if ((object.ReferenceEquals(this.vanioregstdField, value) != true)) {
                    this.vanioregstdField = value;
                    this.RaisePropertyChanged("vanioregstd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string vcuo {
            get {
                return this.vcuoField;
            }
            set {
                if ((object.ReferenceEquals(this.vcuoField, value) != true)) {
                    this.vcuoField = value;
                    this.RaisePropertyChanged("vcuo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string vcuoref {
            get {
                return this.vcuorefField;
            }
            set {
                if ((object.ReferenceEquals(this.vcuorefField, value) != true)) {
                    this.vcuorefField = value;
                    this.RaisePropertyChanged("vcuoref");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string vdesanxstd {
            get {
                return this.vdesanxstdField;
            }
            set {
                if ((object.ReferenceEquals(this.vdesanxstdField, value) != true)) {
                    this.vdesanxstdField = value;
                    this.RaisePropertyChanged("vdesanxstd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string vnumdociderem {
            get {
                return this.vnumdocideremField;
            }
            set {
                if ((object.ReferenceEquals(this.vnumdocideremField, value) != true)) {
                    this.vnumdocideremField = value;
                    this.RaisePropertyChanged("vnumdociderem");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string vnumregstd {
            get {
                return this.vnumregstdField;
            }
            set {
                if ((object.ReferenceEquals(this.vnumregstdField, value) != true)) {
                    this.vnumregstdField = value;
                    this.RaisePropertyChanged("vnumregstd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string vobs {
            get {
                return this.vobsField;
            }
            set {
                if ((object.ReferenceEquals(this.vobsField, value) != true)) {
                    this.vobsField = value;
                    this.RaisePropertyChanged("vobs");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string vrucentrem {
            get {
                return this.vrucentremField;
            }
            set {
                if ((object.ReferenceEquals(this.vrucentremField, value) != true)) {
                    this.vrucentremField = value;
                    this.RaisePropertyChanged("vrucentrem");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string vuniorgrem {
            get {
                return this.vuniorgremField;
            }
            set {
                if ((object.ReferenceEquals(this.vuniorgremField, value) != true)) {
                    this.vuniorgremField = value;
                    this.RaisePropertyChanged("vuniorgrem");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string vuniorgstd {
            get {
                return this.vuniorgstdField;
            }
            set {
                if ((object.ReferenceEquals(this.vuniorgstdField, value) != true)) {
                    this.vuniorgstdField = value;
                    this.RaisePropertyChanged("vuniorgstd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string vusumod {
            get {
                return this.vusumodField;
            }
            set {
                if ((object.ReferenceEquals(this.vusumodField, value) != true)) {
                    this.vusumodField = value;
                    this.RaisePropertyChanged("vusumod");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string vusuregstd {
            get {
                return this.vusuregstdField;
            }
            set {
                if ((object.ReferenceEquals(this.vusuregstdField, value) != true)) {
                    this.vusuregstdField = value;
                    this.RaisePropertyChanged("vusuregstd");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MesaVirtualService.IMesaVirtualService")]
    public interface IMesaVirtualService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMesaVirtualService/GuardaRecepcion", ReplyAction="http://tempuri.org/IMesaVirtualService/GuardaRecepcionResponse")]
        SIGESDOC.Host.MesaVirtualService.RecepcionResponse[] GuardaRecepcion(int idrecepcion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMesaVirtualService/GuardaRecepcion", ReplyAction="http://tempuri.org/IMesaVirtualService/GuardaRecepcionResponse")]
        System.Threading.Tasks.Task<SIGESDOC.Host.MesaVirtualService.RecepcionResponse[]> GuardaRecepcionAsync(int idrecepcion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMesaVirtualService/Recupera_Recepcion", ReplyAction="http://tempuri.org/IMesaVirtualService/Recupera_RecepcionResponse")]
        SIGESDOC.Host.MesaVirtualService.RecepcionResponse Recupera_Recepcion(int idrecepcion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMesaVirtualService/Recupera_Recepcion", ReplyAction="http://tempuri.org/IMesaVirtualService/Recupera_RecepcionResponse")]
        System.Threading.Tasks.Task<SIGESDOC.Host.MesaVirtualService.RecepcionResponse> Recupera_RecepcionAsync(int idrecepcion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMesaVirtualService/GetRecepcions", ReplyAction="http://tempuri.org/IMesaVirtualService/GetRecepcionsResponse")]
        SIGESDOC.Host.MesaVirtualService.RecepcionResponse[] GetRecepcions();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMesaVirtualService/GetRecepcions", ReplyAction="http://tempuri.org/IMesaVirtualService/GetRecepcionsResponse")]
        System.Threading.Tasks.Task<SIGESDOC.Host.MesaVirtualService.RecepcionResponse[]> GetRecepcionsAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMesaVirtualServiceChannel : SIGESDOC.Host.MesaVirtualService.IMesaVirtualService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MesaVirtualServiceClient : System.ServiceModel.ClientBase<SIGESDOC.Host.MesaVirtualService.IMesaVirtualService>, SIGESDOC.Host.MesaVirtualService.IMesaVirtualService {
        
        public MesaVirtualServiceClient() {
        }
        
        public MesaVirtualServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MesaVirtualServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MesaVirtualServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MesaVirtualServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SIGESDOC.Host.MesaVirtualService.RecepcionResponse[] GuardaRecepcion(int idrecepcion) {
            return base.Channel.GuardaRecepcion(idrecepcion);
        }
        
        public System.Threading.Tasks.Task<SIGESDOC.Host.MesaVirtualService.RecepcionResponse[]> GuardaRecepcionAsync(int idrecepcion) {
            return base.Channel.GuardaRecepcionAsync(idrecepcion);
        }
        
        public SIGESDOC.Host.MesaVirtualService.RecepcionResponse Recupera_Recepcion(int idrecepcion) {
            return base.Channel.Recupera_Recepcion(idrecepcion);
        }
        
        public System.Threading.Tasks.Task<SIGESDOC.Host.MesaVirtualService.RecepcionResponse> Recupera_RecepcionAsync(int idrecepcion) {
            return base.Channel.Recupera_RecepcionAsync(idrecepcion);
        }
        
        public SIGESDOC.Host.MesaVirtualService.RecepcionResponse[] GetRecepcions() {
            return base.Channel.GetRecepcions();
        }
        
        public System.Threading.Tasks.Task<SIGESDOC.Host.MesaVirtualService.RecepcionResponse[]> GetRecepcionsAsync() {
            return base.Channel.GetRecepcionsAsync();
        }
    }
}
